begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;
select no_plan();
insert into auth.users(id,email,role,aud) values
  ('00000000-0000-4000-8000-000000000091','row-deck-owner@example.test','authenticated','authenticated');
set local role authenticated;
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000091',true);
select set_config('test.row_deck_scene','{"durationMs":3200,"cameraAngle":"front","equipment":null,"keyframes":[{"timeMs":0,"poses":{}},{"timeMs":3200,"poses":{}}],"studio":{"body":{"x":0,"y":0,"z":0,"rotationX":0,"rotationY":0,"rotationZ":0,"scale":1},"objects":[{"id":"00000000-0000-4000-8000-000000000092","name":"Cable row","slug":"cable-row-machine","x":0,"y":0,"z":0,"rotationX":0,"rotationY":0,"rotationZ":0,"scale":1,"attachment":"none","pulleyHeight":1.35,"machineUse":true,"machinePosition":0.5,"frames":[{"x":0,"y":0,"z":0,"rotationX":0,"rotationY":0,"rotationZ":0,"scale":1,"timeMs":0,"machinePosition":0},{"x":0,"y":0,"z":0,"rotationX":0,"rotationY":0,"rotationZ":0,"scale":1,"timeMs":3200,"machinePosition":1}]}]}}',true);
select set_config('test.row_deck_private',public.create_workshop_exercise(current_setting('test.row_deck_scene')::jsonb)::text,true);
select is((select studio_layout from exercise_scenes where content_id=(select content_id from private_exercises where id=current_setting('test.row_deck_private')::uuid)),current_setting('test.row_deck_scene')::jsonb->'studio','cable row loads with its original contact and travel');
select lives_ok($$select public.save_private_scene(current_setting('test.row_deck_private')::uuid,jsonb_set(current_setting('test.row_deck_scene')::jsonb,'{studio,objects,0,machinePosition}','0.42'))$$,'row travel remains editable');
select throws_ok($$select public.save_private_scene(current_setting('test.row_deck_private')::uuid,jsonb_set(current_setting('test.row_deck_scene')::jsonb,'{studio,objects,0,machinePosition}','1.1'))$$,'23514',null,'row rejects out of range travel');
select set_config('test.row_deck_scene',jsonb_set(current_setting('test.row_deck_scene')::jsonb,'{studio,objects,0,slug}','"pec-deck"')::text,true);
select lives_ok($$select public.save_private_scene(current_setting('test.row_deck_private')::uuid,current_setting('test.row_deck_scene')::jsonb)$$,'pec deck saves with its own moving handles');
select lives_ok($$select public.save_private_metadata(p_private_id => current_setting('test.row_deck_private')::uuid,p_patch => '{"family":"chest-fly"}'::jsonb)$$,'pec deck can be classified as a chest fly');
select is((select f.slug from exercise_families f join exercise_content c on c.family_id=f.id join private_exercises p on p.content_id=c.id where p.id=current_setting('test.row_deck_private')::uuid),'chest-fly','fly classification survives owner save');
select is((select studio_layout from exercise_scenes where content_id=(select content_id from private_exercises where id=current_setting('test.row_deck_private')::uuid)),current_setting('test.row_deck_scene')::jsonb->'studio','pec deck loads with its original contact and travel');
select lives_ok($$select public.save_private_scene(current_setting('test.row_deck_private')::uuid,jsonb_set(current_setting('test.row_deck_scene')::jsonb,'{studio,objects,0,machineMode}','"regular"'))$$,'regular pec deck mode saves');
select lives_ok($$select public.save_private_scene(current_setting('test.row_deck_private')::uuid,jsonb_set(current_setting('test.row_deck_scene')::jsonb,'{studio,objects,0,machineMode}','"reverse"'))$$,'reverse pec deck mode saves');
select is((select studio_layout #>> '{objects,0,machineMode}' from exercise_scenes where content_id=(select content_id from private_exercises where id=current_setting('test.row_deck_private')::uuid)),'reverse','reverse mode survives storage');
select throws_ok($$select public.save_private_scene(current_setting('test.row_deck_private')::uuid,jsonb_set(current_setting('test.row_deck_scene')::jsonb,'{studio,objects,0,machineMode}','"invalid"'))$$,'23514',null,'unknown pec deck mode rejected');
select throws_ok($$select public.save_private_scene(current_setting('test.row_deck_private')::uuid,jsonb_set(current_setting('test.row_deck_scene')::jsonb,'{studio,objects,0,machineMode}','null'))$$,'23514',null,'null pec deck mode rejected');
select throws_ok($$select public.save_private_scene(current_setting('test.row_deck_private')::uuid,jsonb_set(jsonb_set(current_setting('test.row_deck_scene')::jsonb,'{studio,objects,0,machineMode}','"reverse"'),'{studio,objects,0,slug}','"cable-row-machine"'))$$,'23514',null,'reverse mode rejected on row machine');
select lives_ok($$select public.save_private_metadata(p_private_id => current_setting('test.row_deck_private')::uuid,p_patch => '{"family":"reverse-fly"}'::jsonb)$$,'reverse fly has a separate family');
select public.save_private_scene(current_setting('test.row_deck_private')::uuid,current_setting('test.row_deck_scene')::jsonb);
select throws_ok($$select public.save_private_scene(current_setting('test.row_deck_private')::uuid,jsonb_set(current_setting('test.row_deck_scene')::jsonb,'{studio,objects,0,frames,0,machinePosition}','-0.1'))$$,'23514',null,'pec deck rejects invalid frame travel');
select throws_ok($$select public.save_private_scene(current_setting('test.row_deck_private')::uuid,jsonb_set(current_setting('test.row_deck_scene')::jsonb,'{studio,objects,0,machineGrip}','"pronated"'))$$,'23514',null,'pec deck rejects pulldown-only controls');
select public.replace_private_share(current_setting('test.row_deck_private')::uuid,repeat('c',64));
set local role anon;
select is(public.read_shared_private_scene(repeat('c',64))->'studio',current_setting('test.row_deck_scene')::jsonb->'studio','shared scene preserves the pec deck');
reset role;
select is((select count(*)::integer from equipment where slug in ('cable-row-machine','pec-deck')),2,'both equipment filters exist exactly once');
select * from finish();
rollback;
