begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;
select no_plan();
insert into auth.users(id,email,aud,role) values
  ('00000000-0000-4000-8000-000000000081','machine-owner@example.test','authenticated','authenticated'),
  ('00000000-0000-4000-8000-000000000082','machine-other@example.test','authenticated','authenticated');
set local role authenticated;
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000081',true);
select set_config('test.machine_scene','{"durationMs":3200,"cameraAngle":"front","equipment":null,"keyframes":[{"timeMs":0,"poses":{}},{"timeMs":3200,"poses":{}}],"studio":{"body":{"x":0,"y":0,"z":0,"rotationX":0,"rotationY":0,"rotationZ":0,"scale":1},"objects":[{"id":"00000000-0000-4000-8000-000000000083","name":"Machine fixture","slug":"smith-machine","x":0,"y":0,"z":0,"rotationX":0,"rotationY":0,"rotationZ":0,"scale":1,"attachment":"none","pulleyHeight":2.6,"machineUse":true,"machinePosition":0.5,"frames":[{"x":0,"y":0,"z":0,"rotationX":0,"rotationY":0,"rotationZ":0,"scale":1,"timeMs":0,"machinePosition":0},{"x":0,"y":0,"z":0,"rotationX":0,"rotationY":0,"rotationZ":0,"scale":1,"timeMs":3200,"machinePosition":1}]}]}}',true);
select lives_ok($$select public.create_workshop_exercise(jsonb_set(current_setting('test.machine_scene')::jsonb,'{studio,objects,0,slug}','"lat-pulldown-machine"'))$$,'pulldown scene saves');
select lives_ok($$select public.create_workshop_exercise(jsonb_set(jsonb_set(current_setting('test.machine_scene')::jsonb,'{studio,objects,0,slug}','"lat-pulldown-machine"'),'{studio,objects,0,machineGrip}','"supinated"'))$$,'supinated pulldown saves');
select lives_ok($$select public.create_workshop_exercise(jsonb_set(jsonb_set(current_setting('test.machine_scene')::jsonb,'{studio,objects,0,slug}','"lat-pulldown-machine"'),'{studio,objects,0,machineGrip}','"pronated"'))$$,'pronated pulldown saves');
select throws_ok($$select public.create_workshop_exercise(jsonb_set(current_setting('test.machine_scene')::jsonb,'{studio,objects,0,machineGrip}','"pronated"'))$$,'23514',null,'grip on Smith machine rejected');
select throws_ok($$select public.create_workshop_exercise(jsonb_set(jsonb_set(current_setting('test.machine_scene')::jsonb,'{studio,objects,0,slug}','"lat-pulldown-machine"'),'{studio,objects,0,machineGrip}','"neutral"'))$$,'23514',null,'unknown pulldown grip rejected');
select throws_ok($$select public.create_workshop_exercise(jsonb_set(jsonb_set(current_setting('test.machine_scene')::jsonb,'{studio,objects,0,slug}','"lat-pulldown-machine"'),'{studio,objects,0,machineGrip}','null'))$$,'23514',null,'null pulldown grip rejected');
select lives_ok($$select public.create_workshop_exercise(jsonb_set(current_setting('test.machine_scene')::jsonb,'{studio,objects,0,slug}','"leg-press"'))$$,'leg press scene saves');
select set_config('test.machine_private',public.create_workshop_exercise(current_setting('test.machine_scene')::jsonb)::text,true);
select is((select studio_layout from public.exercise_scenes where content_id=(select content_id from public.private_exercises where id=current_setting('test.machine_private')::uuid)),current_setting('test.machine_scene')::jsonb->'studio','owner round trip preserves machine frames');
select lives_ok($$select public.save_private_scene(current_setting('test.machine_private')::uuid,jsonb_set(current_setting('test.machine_scene')::jsonb,'{studio,objects,0,machinePosition}','0.4'))$$,'owner can edit travel');
select throws_ok($$select public.save_private_scene(current_setting('test.machine_private')::uuid,jsonb_set(current_setting('test.machine_scene')::jsonb,'{studio,objects,0,machinePosition}','1.1'))$$,'23514',null,'invalid travel rejected');
select throws_ok($$select public.save_private_scene(current_setting('test.machine_private')::uuid,jsonb_set(current_setting('test.machine_scene')::jsonb,'{studio,objects,0,frames,0,machinePosition}','null'))$$,'23514',null,'null frame travel rejected');
select throws_ok($$select public.save_private_scene(current_setting('test.machine_private')::uuid,jsonb_set(current_setting('test.machine_scene')::jsonb,'{studio,objects,0,slug}','"bench"'))$$,'23514',null,'machine controls on bench rejected');
select throws_ok($$select public.save_private_scene(current_setting('test.machine_private')::uuid,jsonb_set(current_setting('test.machine_scene')::jsonb,'{studio,objects,0,machineUse}','"yes"'))$$,'23514',null,'invalid contact control rejected');
select set_config('test.machine_scene',jsonb_set(jsonb_set(current_setting('test.machine_scene')::jsonb,'{studio,objects,0,slug}','"lat-pulldown-machine"'),'{studio,objects,0,machineGrip}','"pronated"')::text,true);
select public.save_private_scene(current_setting('test.machine_private')::uuid,current_setting('test.machine_scene')::jsonb);
select public.replace_private_share(current_setting('test.machine_private')::uuid,repeat('a',64));
reset role;
select set_config('test.machine_clone',private.clone_exercise_content((select content_id from public.private_exercises where id=current_setting('test.machine_private')::uuid),'submission_editorial',null)::text,true);
select is((select studio_layout from public.exercise_scenes where content_id=current_setting('test.machine_clone')::uuid),current_setting('test.machine_scene')::jsonb->'studio','review clone preserves machine controls');
set local role anon;
select is(public.read_shared_private_scene(repeat('a',64))->'studio',current_setting('test.machine_scene')::jsonb->'studio','shared reader preserves machine controls');
set local role authenticated;
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000082',true);
select throws_ok($$select public.save_private_scene(current_setting('test.machine_private')::uuid,current_setting('test.machine_scene')::jsonb)$$,'P0001','private exercise not found','other account cannot edit');
select is((select count(*)::integer from public.private_exercises where id=current_setting('test.machine_private')::uuid),0,'other account cannot read draft');
reset role;
select * from finish();
rollback;
