begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;
select plan(20);
insert into auth.users(id,email,aud,role) values
  ('00000000-0000-4000-8000-000000000081','studio-owner@example.test','authenticated','authenticated'),
  ('00000000-0000-4000-8000-000000000082','studio-other@example.test','authenticated','authenticated');
set local role authenticated;
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000081',true);
select set_config('test.studio_private',public.save_private_exercise(p_name=>'Studio Draft')::text,true);
select set_config('test.studio_payload','{"durationMs":3200,"cameraAngle":"front","equipment":null,"keyframes":[{"timeMs":0,"poses":{}},{"timeMs":3200,"poses":{}}],"studio":{"body":{"x":1,"y":0,"z":0,"rotationX":0,"rotationY":45,"rotationZ":0,"scale":1},"objects":[{"id":"00000000-0000-4000-8000-000000000083","name":"My cable","slug":"cable-machine","x":2,"y":0,"z":-1,"rotationX":0,"rotationY":90,"rotationZ":0,"scale":1,"attachment":"left","pulleyHeight":2.2}]}}',true);
select set_config('test.studio_scene',public.save_private_scene(current_setting('test.studio_private')::uuid,current_setting('test.studio_payload')::jsonb)::text,true);
select is((select studio_layout from public.exercise_scenes where id=current_setting('test.studio_scene')::uuid),current_setting('test.studio_payload')::jsonb->'studio','layout is saved exactly');
select throws_ok($$select public.save_private_scene(current_setting('test.studio_private')::uuid,jsonb_set(current_setting('test.studio_payload')::jsonb,'{studio,body,scale}','0'))$$,'23514',null,'invalid transform rejected');
select throws_ok($$select public.save_private_scene(current_setting('test.studio_private')::uuid,jsonb_set(current_setting('test.studio_payload')::jsonb,'{studio,objects,0,pulleyHeight}','20'))$$,'23514',null,'invalid cable height rejected');
select throws_ok($$select public.save_private_scene(current_setting('test.studio_private')::uuid,jsonb_set(current_setting('test.studio_payload')::jsonb,'{studio,objects}',(current_setting('test.studio_payload')::jsonb#>'{studio,objects}')||(current_setting('test.studio_payload')::jsonb#>'{studio,objects}')))$$,'23514',null,'duplicate objects rejected');
select is((select studio_layout from public.exercise_scenes where id=current_setting('test.studio_scene')::uuid),current_setting('test.studio_payload')::jsonb->'studio','invalid save leaves original layout intact');
select set_config('test.studio_share',public.replace_private_share(current_setting('test.studio_private')::uuid,repeat('c',64))::text,true);
reset role;
select set_config('test.studio_clone',private.clone_exercise_content((select content_id from public.private_exercises where id=current_setting('test.studio_private')::uuid),'submission_editorial',null)::text,true);
select is((select studio_layout from public.exercise_scenes where content_id=current_setting('test.studio_clone')::uuid),current_setting('test.studio_payload')::jsonb->'studio','review snapshot retains complete layout');
set local role anon;
select is(public.read_shared_private_scene(repeat('c',64))->'studio',current_setting('test.studio_payload')::jsonb->'studio','authorized shared reader includes layout');
reset role;
select ok(pg_get_functiondef('public.read_render_scene(uuid)'::regprocedure) like '%scene.studio_layout%','render reader includes studio layout');
select ok(pg_get_functiondef('public.read_render_refresh_scene(uuid)'::regprocedure) like '%s.studio_layout%','refresh reader includes studio layout');
set local role authenticated;
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000082',true);
select throws_ok($$select public.save_private_scene(current_setting('test.studio_private')::uuid,current_setting('test.studio_payload')::jsonb)$$,'P0001','private exercise not found','other user cannot edit layout');
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000081',true);
select public.save_private_scene(current_setting('test.studio_private')::uuid,current_setting('test.studio_payload')::jsonb-'studio');
select is((select studio_layout from public.exercise_scenes where id=current_setting('test.studio_scene')::uuid),null::jsonb,'legacy saves clear layout');
select lives_ok($$select public.save_private_scene(current_setting('test.studio_private')::uuid,current_setting('test.studio_payload')::jsonb)$$,'layout can be restored');
select set_config('test.bar_payload',jsonb_set(jsonb_set(current_setting('test.studio_payload')::jsonb,'{studio,objects,0,slug}','"barbell"'),'{studio,objects,0,attachment}','"both"')::text,true);
select lives_ok($$select public.save_private_scene(current_setting('test.studio_private')::uuid,current_setting('test.bar_payload')::jsonb)$$,'both-hand barbell grip is saved');
select set_config('test.new_workshop',public.create_workshop_exercise(current_setting('test.bar_payload')::jsonb)::text,true);
select is((select exercise_content.name from public.private_exercises join public.exercise_content on exercise_content.id=private_exercises.content_id where private_exercises.id=current_setting('test.new_workshop')::uuid),'Untitled exercise','workshop creates a placeholder name without requiring classifications');
select is((select studio_layout->'objects'->0->>'attachment' from public.exercise_scenes where content_id=(select content_id from public.private_exercises where id=current_setting('test.new_workshop')::uuid)),'both','new draft and scene are saved together');
select set_config('test.drafts_before',(select count(*) from public.private_exercises)::text,true);
select throws_ok($$select public.create_workshop_exercise(jsonb_set(current_setting('test.bar_payload')::jsonb,'{studio,body,scale}','0'))$$,'23514',null,'invalid initial layout rolls back draft creation');
select is((select count(*)::integer from public.private_exercises),current_setting('test.drafts_before')::integer,'failed creation leaves no orphan draft');
select set_config('test.frame_payload',jsonb_set(current_setting('test.bar_payload')::jsonb,'{studio,objects,0,frames}',jsonb_build_array((current_setting('test.bar_payload')::jsonb#>'{studio,body}')||'{"timeMs":0}',(current_setting('test.bar_payload')::jsonb#>'{studio,body}')||'{"timeMs":1600,"y":1.6}'))::text,true);
select lives_ok($$select public.save_private_scene(current_setting('test.studio_private')::uuid,current_setting('test.frame_payload')::jsonb)$$,'equipment movement keyframes survive saving');
select throws_ok($$select public.save_private_scene(current_setting('test.studio_private')::uuid,jsonb_set(current_setting('test.frame_payload')::jsonb,'{studio,objects,0,frames,1,timeMs}','4000'))$$,'23514',null,'equipment frames cannot exceed scene duration');
set local role anon;
select throws_ok($$select public.create_workshop_exercise(current_setting('test.bar_payload')::jsonb)$$,'42501',null,'anonymous visitors cannot create workshop drafts');
select * from finish();
rollback;
