import { parseWorkshopNumber } from "./workshop-number";

export type WorkshopLanguage = "en" | "he";
export type WorkshopTranslationParams = Record<string, string | number>;

// English source text is the key, so unknown scientific names remain readable.
export const workshopHebrew: Readonly<Record<string, string>> = {
  "Create your own movement": "יצירת תנועה משלכם",
  "Add equipment, pose the start and finish, then preview and save. Equipment does not choose your exercise.": "הוסיפו ציוד, קבעו תנוחות התחלה וסיום, ואז צפו ושמרו. הציוד לא בוחר את התרגיל שלכם.",
  "Free cable movement": "תנועה חופשית בכבל",
  "For deadlifts, pulls or any cable movement. Move hands, feet, hips and torso freely.": "לדדליפט, משיכות או כל תנועה בכבל. הזיזו ידיים, רגליים, ירכיים וגו בחופשיות.",
  "Choose how to use the cable": "בחירת אופן השימוש בכבל",
  "Seated row links the seat, feet and handle. Free cable movement lets you pose the whole body.": "חתירה בישיבה מצמידה את המושב, הרגליים והידית. תנועה חופשית בכבל מאפשרת לשנות את תנוחת הגוף כולו.",
  "Use seated row": "שימוש בחתירה בישיבה",
  "Build movement with poses": "בניית תנועה באמצעות תנוחות",
  "Choose Edit start or Edit finish, then drag hands and feet. Use joint controls for hips, knees and torso. Each change updates that pose immediately.": "בחרו עריכת התחלה או עריכת סיום, ואז גררו ידיים ורגליים. השתמשו בפקדי המפרקים לירכיים, לברכיים ולגו. כל שינוי מעדכן מיד את התנוחה שנבחרה.",
  "Edit start": "עריכת התחלה", "Edit finish": "עריכת סיום",
  "Match return to start": "התאמת החזרה להתחלה",
  "Play interpolates between your poses. Match return to start makes a complete loop. Add extra moments in Timeline.": "הניגון מחבר בין התנוחות שלכם. התאמת החזרה להתחלה יוצרת לולאה מלאה. אפשר להוסיף רגעים בציר הזמן.",
  "Cable attachment and grip": "אביזר ואחיזה בכבל",
  "Cable position and pulley": "מיקום הכבל והגלגלת",
  "Precise placement": "מיקום מדויק",
  "Drag options": "אפשרויות גרירה",
  "Save": "שמירה", "← My exercises": "התרגילים שלי ←", "← Exercise details": "פרטי התרגיל ←",
  "Save & add details →": "שמירה והוספת פרטים ←",
  "Drag to rotate the camera. Choose Move to reposition the figure or equipment.": "גררו לסיבוב המצלמה. בחרו הזזה כדי למקם את הדמות או הציוד.",
  "controls contact": "שולט במגע", "controls this arm": "שולט ביד זו",
  "Equipment": "ציוד", "Contacts": "מגעים", "Pose": "תנוחה", "Timeline": "ציר זמן", "View": "תצוגה", "Setups": "סידורים", "Settings": "הגדרות",
  "Selected equipment": "ציוד נבחר", "View and muscles": "תצוגה ושרירים",
  "More": "עוד", "Preview & save": "תצוגה ושמירה", "Exit workshop": "יציאה מהסדנה", "Hands & feet": "ידיים ורגליים",
  "Full screen is unavailable in this browser.": "מסך מלא אינו זמין בדפדפן הזה.",
  "Body joint": "מפרק בגוף",
  "Equipment movement": "תנועת ציוד",
  "Select equipment to set grips or supports.": "בחרו ציוד כדי לקבוע אחיזה או תמיכה.",
  "This item has no grip or support controls. Use Position to place it.": "לפריט זה אין פקדי אחיזה או תמיכה. השתמשו במיקום כדי למקם אותו.",
  "Bench body position": "תנוחת גוף על הספסל",
  "Body position on bench": "תנוחת גוף על הספסל",
  "Sit": "ישיבה",
  "Lie face up": "שכיבה על הגב",
  "Lie face down": "שכיבה על הבטן",
  "Chest supported": "תמיכת חזה",
  "Sitting direction": "כיוון הישיבה",
  "Leave bench": "עזיבת הספסל",
  "Flat": "שטוח",
  "Incline": "משופע",
  "Upright": "זקוף",
  "The figure follows the bench. Leave bench to pose freely.": "הדמות נעה עם הספסל. עזבו את הספסל כדי לשנות תנוחה בחופשיות.",
  "Tutorial": "מדריך",
  "Workshop tutorial": "מדריך הסדנה",
  "Close tutorial": "סגירת המדריך",
  "Finish tutorial": "סיום המדריך",
  "Show these controls": "הצגת הפקדים האלה",
  "Previous tip": "השלב הקודם",
  "Next tip": "השלב הבא",
  "Choose your equipment": "בחרו את הציוד שלכם",
  "Place the figure and equipment": "מקמו את הדמות והציוד",
  "Set grips and supports": "הגדירו אחיזות ותמיכות",
  "Pose the body": "קבעו את תנוחת הגוף",
  "Build the movement": "בנו את התנועה",
  "Check your full repetition": "בדקו חזרה מלאה",
  "Choose what the preview shows": "בחרו מה מוצג בתצוגה המקדימה",
  "Reuse setups and undo edits": "השתמשו שוב בסידורי ציוד ובטלו עריכות",
  "Name and save your exercise": "תנו שם לתרגיל ושמרו אותו",
  "Add equipment to build any movement you want. A machine does not define the exercise.": "הוסיפו ציוד כדי ליצור כל תנועה שתרצו. המכונה אינה קובעת את התרגיל.",
  "Search the equipment pictures, favorite items, or start from an exercise example. Examples replace the scene; Undo brings it back.": "חפשו בתמונות הציוד, שמרו פריטים במועדפים או התחילו מדוגמת תרגיל. דוגמאות מחליפות את הסצנה; ביטול מחזיר אותה.",
  "Select the figure or an item in your scene. Move it with the mouse, rotate it, or enter exact coordinates and scale.": "בחרו את הדמות או פריט בסצנה. הזיזו אותו בעכבר, סובבו אותו או הזינו מיקום וגודל מדויקים.",
  "Use Front and Side views to check placement. Lower movement sensitivity for small adjustments.": "בדקו את המיקום במבט מלפנים ומהצד. הורידו את רגישות התנועה להתאמות קטנות.",
  "Contact controls let you hold weights, attach cable handles or cuffs, sit or lie on a bench, and link machine handles.": "פקדי המגע מאפשרים להחזיק משקולות, לחבר ידיות כבל או רצועות, לשבת או לשכב על ספסל ולחבר ידיות מכונה.",
  "Leave machine or Release restores free posing. Set bench angle, palm direction, and elbow locks when your movement needs them.": "עזיבת המכונה או שחרור מאפשרים שוב לשנות תנוחה בחופשיות. הגדירו זווית ספסל, כיוון כפות ידיים ונעילת מרפקים לפי צורכי התנועה.",
  "Use Pose hands and feet to drag limbs, or Pose body to choose a joint and adjust its angles.": "השתמשו בתנוחת ידיים ורגליים כדי לגרור גפיים, או בתנוחת גוף כדי לבחור מפרק ולשנות את זוויותיו.",
  "Held equipment drives its arm. Release it for free posing. Edit this pose changes one moment; Apply to all poses changes every moment.": "ציוד מוחזק מניע את הזרוע. שחררו אותו לשינוי תנוחה חופשי. עריכת התנוחה הזו משנה רגע אחד; החלה על כל התנוחות משנה את כל הרגעים.",
  "Choose a starting pose, add a finish pose, and return to the start. Select each timeline moment before editing it.": "בחרו תנוחת התחלה, הוסיפו תנוחת סיום וחזרו להתחלה. בחרו כל רגע בציר הזמן לפני עריכתו.",
  "Animate selected item lets equipment move between poses. Copy poses, mirror sides, adjust duration, or match the loop end to the start.": "הנפשת הפריט הנבחר מאפשרת לציוד לנוע בין תנוחות. העתיקו תנוחות, החליפו צדדים, שנו משך או התאימו את סוף הלולאה להתחלה.",
  "Play the movement, slow the preview, and scrub the timeline. View start and View finish inspect exact moments.": "הפעילו את התנועה, האטו את התצוגה ועברו בציר הזמן. הצגת התחלה והצגת סיום מאפשרות לבדוק רגעים מדויקים.",
  "Compare start and finish shows both poses together. Check grips, supports, feet, and the return from different views. Reach warnings help find missed contacts.": "השוואת התחלה וסיום מציגה את שתי התנוחות יחד. בדקו אחיזות, תמיכות, רגליים והחזרה ממבטים שונים. אזהרות טווח עוזרות לאתר מגע חסר.",
  "Use the preview controls to choose muscle highlights, isolate anatomy, change views, pan, and zoom.": "בפקדי התצוגה אפשר לבחור הדגשת שרירים, לבודד מבנים אנטומיים, לשנות מבטים, להזיז את המצלמה ולהגדיל.",
  "Highlights are optional. Focus mode gives you more room while keeping playback and saving available.": "הדגשות הן אופציונליות. מצב מיקוד נותן יותר מקום ומשאיר את ההפעלה והשמירה זמינות.",
  "Undo and Redo restore complete edits. Edit history lists recent changes; Recovery and shortcuts includes saved-scene recovery and keyboard controls.": "ביטול וביצוע חוזר משחזרים עריכות שלמות. היסטוריית העריכה מציגה שינויים אחרונים; שחזור וקיצורים כולל שחזור סצנה שמורה וקיצורי מקלדת.",
  "Personal equipment setups reuse placements and contacts. Save a setup in Advanced editing, then apply it to another exercise.": "סידורי ציוד אישיים מאפשרים להשתמש שוב במיקומים ובמגעים. שמרו סידור בעריכה מתקדמת והחילו אותו על תרגיל אחר.",
  "Give the exercise a name and Save privately. Named edits also save automatically; check the save status and retry if a save fails.": "תנו לתרגיל שם ושמרו באופן פרטי. עריכות עם שם נשמרות גם אוטומטית; בדקו את מצב השמירה ונסו שוב אם השמירה נכשלת.",
  "Add optional details opens muscles, classifications, and instructions. Your exercise stays private. Reopen this walkthrough with Tutorial whenever you need it.": "הוספת פרטים אופציונליים פותחת שרירים, סיווגים והוראות. התרגיל נשאר פרטי. אפשר לפתוח שוב את המדריך בכל עת דרך כפתור המדריך.",
  "Placement": "מיקום",
  "Contact": "מגע",
  "Focus mode": "מצב מיקוד",
  "Exit focus mode": "יציאה ממצב מיקוד",
  "Compare start and finish": "השוואת התחלה וסיום",
  "Close comparison": "סגירת ההשוואה",
  "Start and finish comparison": "השוואת התחלה וסיום",
  "Start pose comparison": "השוואת תנוחת ההתחלה",
  "Finish pose comparison": "השוואת תנוחת הסיום",
  "Rotate, pan or zoom either view. Both views use the same camera. Editing controls still affect the selected pose.": "סובבו, הזיזו או הגדילו כל תצוגה. שתי התצוגות משתמשות באותה מצלמה. פקדי העריכה עדיין משפיעים על התנוחה שנבחרה.",
  "Edit history": "היסטוריית עריכה",
  "No edits yet": "אין עריכות עדיין",
  "Latest edit first. Undo and Redo restore one edit at a time.": "העריכה האחרונה מוצגת ראשונה. ביטול וביצוע חוזר משחזרים עריכה אחת בכל פעם.",
  "Repetition markers": "סימוני החזרה",
  "Personal equipment setups": "סידורי ציוד אישיים",
  "Setup name": "שם הסידור",
  "Save equipment setup": "שמירת סידור ציוד",
  "Equipment setups saved on this device.": "סידורי הציוד נשמרו במכשיר זה.",
  "Equipment setups are unavailable on this device.": "סידורי ציוד אינם זמינים במכשיר זה.",
  "Could not save equipment setups. Your scene is unchanged.": "לא ניתן לשמור את סידורי הציוד. הסצנה לא השתנתה.",
  "Enter a setup name of 1 to 60 characters and check the scene.": "הזינו שם סידור באורך 1 עד 60 תווים ובדקו את הסצנה.",
  "Remove a setup before saving another. Limit: 12.": "הסירו סידור לפני שמירת סידור נוסף. המגבלה היא 12.",
  "Save placement, contacts, pulley height and camera on this device. Applying replaces equipment and body placement, keeps your poses and duration, and can be undone. Check contacts before saving.": "שמרו מיקום, מגעים, גובה גלגלת ומצלמה במכשיר זה. החלה מחליפה ציוד ומיקום גוף, שומרת על התנוחות ומשך התנועה וניתנת לביטול. בדקו מגעים לפני השמירה.",
  "Pose hands and feet": "מיקום ידיים ורגליים",
  "Drag a hand or foot using its round button": "גררו יד או כף רגל בעזרת הכפתור העגול שלה",
  "Use Pose hands and feet beside the preview for free limbs. Select a machine for linked contacts, or use Advanced editing for joint angles.": "השתמשו במיקום ידיים ורגליים ליד התצוגה המקדימה לאיברים חופשיים. בחרו מכונה למגעים מחוברים, או השתמשו בעריכה מתקדמת לזוויות המפרקים.",
  "Drag {limb}": "גרירת {limb}",
  "Drag this hand or foot. Arrow keys also move it; Escape cancels.": "גררו את היד או כף הרגל. אפשר להזיז גם עם מקשי החצים; Escape מבטל.",
  "Drag a hand or foot using its round button. Elbows and knees follow. Arrow keys move the selected handle; Shift takes a larger step. Escape cancels. Use Front and Side views to move in different directions.": "גררו יד או כף רגל בעזרת הכפתור העגול שלה. המרפקים והברכיים עוקבים. מקשי החצים מזיזים את הידית שנבחרה; Shift מגדיל את הצעד. Escape מבטל. השתמשו במבט מלפנים ומהצד כדי להזיז בכיוונים שונים.",
  "The moved limb changes in all poses.": "האיבר שהוזז משתנה בכל התנוחות.",
  "Only the displayed pose changes. Undo restores the whole drag.": "רק התנוחה המוצגת משתנה. ביטול מחזיר את כל הגרירה.",
  "Choose Edit this moment to pose the displayed time.": "בחרו בעריכת הרגע הזה כדי לשנות את התנוחה בזמן המוצג.",
  "Leave the machine to pose hands and feet freely. Move its handles to keep contact.": "עזבו את המכונה כדי למקם ידיים ורגליים בחופשיות. הזיזו את הידיות שלה כדי לשמור על המגע.",
  "Choose Free posing in Movement setup to move hands and feet freely.": "בחרו במיקום חופשי בהגדרת התנועה כדי להזיז ידיים ורגליים בחופשיות.",
  "Stand up to move feet freely. Seating keeps feet supported.": "עמדו כדי להזיז את כפות הרגליים בחופשיות. הישיבה שומרת על התמיכה שלהן.",
  "Use editable equipment or remove the attached equipment before posing this limb.": "השתמשו בציוד הניתן לעריכה או הסירו את הציוד המחובר לפני שינוי תנוחת האיבר הזה.",
  "Move the attached equipment to pose this limb, or release it first.": "הזיזו את הציוד המחובר כדי לשנות את תנוחת האיבר הזה, או שחררו אותו קודם.",
  "This target is beyond the limb's reach or joint limits. The closest pose within joint limits is shown.": "הנקודה הזאת מחוץ לטווח ההגעה או לגבולות המפרק. מוצגת התנוחה הקרובה ביותר בגבולות המפרק.",
  "Foot contact changed. Check the sole and floor from Side view before saving.": "המגע של כף הרגל השתנה. בדקו את הסוליה והרצפה במבט מהצד לפני השמירה.",
  "Move with mouse": "הזזה עם העכבר",
  "Mouse movement": "הזזה בעכבר",
  "Object drag direction": "כיוון גרירת הפריט",
  "Across view · includes height": "לרוחב התצוגה · כולל גובה",
  "Along floor": "לאורך הרצפה",
  "Drag start": "גרירת ההתחלה",
  "Drag finish": "גרירת הסיום",
  "Drag {equipment} handle": "גרירת ידית {equipment}",
  "Drag this handle. Arrow keys also move it; Escape cancels a drag.": "גררו את הידית. אפשר להזיז גם עם מקשי החצים; Escape מבטל גרירה.",
  "Drag equipment directly. Use the round grab buttons to move machine handles. Use Side view to drag up, down, toward or away from the body.": "גררו את הציוד ישירות. הכפתורים העגולים מזיזים את ידיות המכונה. השתמשו במבט מהצד כדי לגרור למעלה, למטה, אל הגוף או הרחק ממנו.",
  "Drag equipment to move it. Round grab buttons move machine handles. Use Camera to look around.": "גררו ציוד כדי להזיז אותו. הכפתורים העגולים מזיזים ידיות מכונה. השתמשו במצלמה כדי להביט מסביב.",
  "Move the handle with your mouse to set the start or finish. The return updates automatically.": "הזיזו את הידית עם העכבר כדי לקבוע התחלה או סיום. תנועת החזרה מתעדכנת אוטומטית.",
  "Start handle height meters": "גובה הידית בהתחלה במטרים",
  "Finish handle height meters": "גובה הידית בסיום במטרים",
  "Handle height meters": "גובה הידית במטרים",
  "Set different start and finish heights to pull upward or downward. Heights are above the machine base. The pulley stays fixed; the cable angles toward your hands. Lower the height or shorten the range if a hand cannot reach.": "קבעו גבהים שונים בהתחלה ובסיום כדי למשוך כלפי מעלה או מטה. הגובה נמדד מעל בסיס המכונה. הגלגלת נשארת במקום והכבל פונה לכפות הידיים. אם היד אינה מגיעה, הנמיכו את הגובה או קצרו את הטווח.",
  "Changes handle height at the editing moment. The seat, footplates and pulley stay in place.": "משנה את גובה הידית ברגע הנערך. המושב, משטחי הרגליים והגלגלת נשארים במקום.",
  "Which way do your palms face?": "לאיזה כיוון פונות כפות הידיים?",
  "Where do your elbows move?": "לאן נעים המרפקים?",
  "Both hands use these choices. Check the palms and wrists at the start and finish.": "הבחירות חלות על שתי הידיים. בדקו את כפות הידיים ושורשי כפות הידיים בהתחלה ובסיום.",
  "Check both hands at start": "בדיקת שתי הידיים בהתחלה",
  "Check both hands at finish": "בדיקת שתי הידיים בסיום",
  "Adjust start and finish": "התאמת ההתחלה והסיום",
  "Use standard palm and elbow choices": "בחירות רגילות לכפות הידיים ולמרפקים",
  "Advanced timeline": "ציר זמן מתקדם",
  "Workshop editor": "עורך הסדנה",
  "Keyboard shortcuts": "קיצורי מקלדת",
  "Duplicate selected equipment": "שכפול הציוד שנבחר",
  "Remove selected equipment": "הסרת הציוד שנבחר",
  "Play / pause": "ניגון / השהיה",
  "Previous / next pose": "תנוחה קודמת / הבאה",
  "Move with mouse / Camera": "הזזה בעכבר / מצלמה",
  "Show shortcuts": "הצגת קיצורים",
  "Return to camera / Close shortcuts": "חזרה למצלמה / סגירת הקיצורים",
  "Click the preview or focus the workshop to use playback and pose shortcuts. Text fields keep their own Undo. Space still activates focused buttons; arrows still adjust sliders and handles.": "לחצו על התצוגה המקדימה או העבירו את המיקוד לסדנה כדי להשתמש בקיצורי ניגון ותנוחות. בשדות טקסט נשמר הביטול הרגיל. רווח מפעיל כפתור ממוקד; החצים ממשיכים לכוונן מחוונים וידיות.",
  "Undo · Ctrl / ⌘ + Z": "ביטול · Ctrl / ⌘ + Z",
  "Redo · Ctrl / ⌘ + Shift + Z · Ctrl + Y": "ביצוע מחדש · Ctrl / ⌘ + Shift + Z · Ctrl + Y",
  "Seat": "מושב",
  "not used": "לא בשימוש",
  "Text scene summary": "תקציר הסצנה בטקסט",
  "3D exercise preview": "תצוגה מקדימה תלת־ממדית של התרגיל",
  "Muscle highlights and credits": "הדגשת שרירים וקרדיטים",
  "Credits and licenses": "קרדיטים ורישיונות",
  "No equipment": "ללא ציוד",
  "Nothing selected.": "לא נבחר פריט.",
  "Muscle highlight:": "הדגשת שריר:",
  "No muscle highlight.": "ללא הדגשת שריר.",
  "Only selected anatomy is shown.": "מוצגת רק האנטומיה שנבחרה.",
  "Whole body is shown.": "מוצג הגוף כולו.",
  "Body support is attached to a bench.": "תמיכת הגוף מחוברת לספסל.",
  "No bench support is attached.": "אין תמיכת ספסל מחוברת.",
  "No equipment contact is engaged.": "אין מגע מחובר לציוד.",
  "machine contact engaged": "מגע המכונה מחובר",
  "{side} hand attachment": "חיבור ליד {side}",
  "both hands attached": "חיבור לשתי הידיים",
  "{count} poses over {duration} seconds. Current preview time: {time} seconds.": "{count} תנוחות במשך {duration} שניות. זמן התצוגה כעת: {time} שניות.",
  "body": "גוף",
  "equipment": "ציוד",
  "Use Opposite side and fading to inspect hands, feet and supports at the start and finish.": "השתמשו בצד הנגדי ובעמעום כדי לבדוק ידיים, כפות רגליים ותמיכות בהתחלה ובסיום.",
  "Pull the bar down toward the upper chest; keep the seat contact.": "משכו את המוט מטה לעבר החזה העליון ושמרו על המגע עם המושב.",
  "Move the bar along its guides; keep both feet planted.": "הזיזו את המוט לאורך המסילות ושמרו על שתי כפות הרגליים נטועות.",
  "Push the platform away, then return while keeping the back supported.": "דחפו את המשטח והרפו בחזרה תוך שמירה על תמיכת הגב.",
  "Move through the chosen travel and inspect the intended contacts.": "נועו לאורך הטווח שנבחר ובדקו את המגעים הרצויים.",
  "Open Advanced editing": "פתיחת עריכה מתקדמת",
  "Inspect placement · ": "בדיקת מיקום · ",
  "In Advanced, select this machine and choose Stop animation and edit placement, then create the repetition again. One Undo restores its previous travel.": "בעריכה מתקדמת בחרו את המכונה ועצרו את ההנפשה לעריכת המיקום. לאחר מכן צרו שוב את החזרה. ביטול אחד מחזיר את התנועה הקודמת.",
  "Check that both endpoint percentages are between 0 and 100, then try again.": "ודאו ששני אחוזי הקצה בין 0 ל־100, ואז נסו שוב.",
  "Reset to example": "איפוס לדוגמה",
  "Reset to example replaces the whole scene in one Undo step. Your chosen muscle highlight is kept.": "איפוס לדוגמה מחליף את כל הסצנה. ביטול אחד מחזיר אותה. הדגשת השרירים שבחרתם נשמרת.",
  "Holding or attaching replaces contacts in the chosen hand and clears their elbow locks. An engaged machine is released. One Undo restores the scene.": "אחיזה או חיבור מחליפים את המגעים ביד הנבחרת ומסירים את נעילות המרפקים. מכונה פעילה משתחררת. ביטול אחד מחזיר את הסצנה.",
  "Changing the attachment or cuff position replaces competing hand contacts and clears their locks. One Undo restores the scene.": "שינוי הידית או מיקום הרצועה מחליף מגעים מתחרים ביד ומסיר את נעילותיהם. ביטול אחד מחזיר את הסצנה.",
  "Machine contacts linked": "מגעי המכונה מחוברים",
  "No held contact selected": "לא נבחר מגע אחיזה",
  "Editing pose {number} · {time}": "עריכת תנוחה {number} · {time}",
  "Demonstration caption: ": "כתובית ההדגמה: ",
  "Start: check hands, feet and supports.": "התחלה: בדקו את הידיים, כפות הרגליים והתמיכות.",
  "Return slowly to the start; keep the same contacts.": "חזרו לאט להתחלה ושמרו על אותם מגעים.",
  "Use Play to watch the short repetition. Playback starts only when you choose it.": "בחרו הפעלה כדי לצפות בחזרה הקצרה. התצוגה נעה רק לאחר בחירתכם.",
  "Equipment and figure bounds overlap. Inspect from both sides; empty space inside a machine can also trigger this advisory.": "תחומי הציוד והדמות חופפים. בדקו משני הצדדים. גם חלל ריק במכונה עשוי לגרום להתרעה זו.",
  "Repair: move this item away using Up or Position coordinates, then inspect again. Held items and linked supports are excluded.": "תיקון: הרחיקו את הפריט בעזרת למעלה או קואורדינטות המיקום, ואז בדקו שוב. פריטים מוחזקים ותמיכות מחוברות אינם נכללים.",
  "Placement is locked while editing travel. Use Stop animation and edit placement to reposition the machine.": "המיקום נעול בזמן עריכת התנועה. בחרו עצירת הנפשה ועריכת מיקום כדי למקם את המכונה מחדש.",
  "Choose equipment": "בחירת ציוד",
  "Start and finish": "התחלה וסיום",
  "Preview": "תצוגה מקדימה",
  "Name and save": "שם ושמירה",
  "Quick create": "יצירה מהירה",
  "Advanced editing": "עריכה מתקדמת",
  "Editor mode": "מצב עריכה",
  "Language": "שפה",
  "Workshop language": "שפת הסדנה",
  "Back": "חזרה",
  "Next": "הבא",
  "Start": "התחלה",
  "Finish": "סיום",
  "End": "סוף",
  "Return": "חזרה להתחלה",
  "Close": "סגירה",
  "Add equipment": "הוספת ציוד",
  "Create repetition": "יצירת חזרה",
  "Exercise name": "שם התרגיל",
  "Save privately": "שמירה פרטית",
  "Saving…": "שומר…",
  "Saved privately": "נשמר באופן פרטי",
  "Your private draft": "הטיוטה הפרטית שלך",
  "Add optional details": "הוספת פרטים אופציונליים",
  "Arms long": "ידיים ישרות",
  "Handle near torso": "ידית קרובה לגוף",
  "Arms open": "ידיים פתוחות",
  "Hands together": "ידיים יחד",
  "View start": "הצגת התחלה",
  "View finish": "הצגת סיום",
  "Reset this adjustment": "איפוס התאמה זו",
  "Small range": "טווח קטן",
  "Full range": "טווח מלא",
  "Adjust fit": "התאמת גודל",
  "Smaller": "קטן יותר",
  "Standard": "רגיל",
  "Larger": "גדול יותר",
  "Cable row": "חתירה בכבל",
  "Pec deck": "פרפר",
  "Reverse pec deck": "פרפר הפוך",
  "Cable machine": "מכונת כבל",
  "Adjustable bench": "ספסל מתכוונן",
  "Squat rack": "כלוב סקוואט",
  "Barbell": "מוט משקולות",
  "Dumbbell": "משקולת יד",
  "Kettlebell": "קטלבל",
  "Lat pulldown machine": "מכונת משיכה עליונה",
  "Smith machine": "מכונת סמית",
  "Leg press": "לחיצת רגליים",
  "Start from an example": "התחלה מדוגמה",
  "Supports and contacts": "תמיכות ומגעים",
  "Regular": "רגיל",
  "Reverse": "הפוך",
  "Continue creating": "המשך עריכה",
  "Private": "פרטי",
  "Creation progress": "התקדמות היצירה",
  "Creation steps": "שלבי היצירה",
  "Choose an example to see a complete movement, or add equipment to your current scene.": "אפשר לבחור דוגמה לצפייה בתנועה מלאה, או להוסיף ציוד לסצנה הנוכחית.",
  "Pull to the torso; elbows stay beside the body.": "משיכה אל הגוף, כשהמרפקים נשארים לצד הגוף.",
  "Close both arms in front of the chest.": "סגירת שתי הידיים לפני החזה.",
  "Open both arms with the chest supported.": "פתיחת שתי הידיים כשהחזה נתמך.",
  "Examples replace the current scene in one Undo step. Your chosen muscle highlight is kept.": "דוגמה מחליפה את הסצנה הנוכחית. ביטול אחד מחזיר אותה. הדגשת השרירים שבחרת נשמרת.",
  "Personal templates are available in": "תבניות אישיות זמינות ב",
  "My exercises": "התרגילים שלי",
  "Pec deck mode": "מצב מכונת פרפר",
  "Adjust travel first; the machine frame and supports stay in place.": "תחילה יש להתאים את טווח התנועה. מסגרת המכונה והתמיכות נשארות במקום.",
  "Creates a smooth Start → Finish → Return. Body poses, other objects and selected muscles are kept.": "יוצר תנועה חלקה מהתחלה לסיום ובחזרה. תנוחות הגוף, שאר הפריטים והשרירים שנבחרו נשמרים.",
  "Select a machine for automatic contacts, or use Advanced editing to pose weights and body joints.": "בחרו מכונה למגעים אוטומטיים, או השתמשו בעריכה מתקדמת להתאמת משקולות ומפרקי הגוף.",
  "Pose body in Advanced": "התאמת הגוף בעריכה מתקדמת",
  "Scales the figure and engaged machine together to keep their supports aligned. Undo restores the previous fit.": "משנה את גודל הדמות והמכונה יחד כדי לשמור על התאמת התמיכות. ביטול מחזיר את הגודל הקודם.",
  "No machine engaged. Check body and floor contact in the preview.": "אין מכונה מחוברת. בדקו מגע בין הגוף לרצפה בתצוגה המקדימה.",
  "Seat / torso": "מושב / גוף",
  "Back / chest": "גב / חזה",
  "Both feet": "שתי כפות הרגליים",
  "Both hands": "שתי הידיים",
  "linked": "מחובר",
  "check": "לבדיקה",
  "Inspect start and finish from both sides. Linked supports still need a visual check.": "בדקו את ההתחלה והסיום משני הצדדים. גם תמיכות מחוברות דורשות בדיקה חזותית.",
  "A hand cannot reach its handle. Use a smaller range or reset fit; inspect the wrist from the opposite side.": "יד אינה מגיעה לידית שלה. הקטינו את הטווח או אפסו את התאמת הגודל. בדקו את שורש כף היד מהצד הנגדי.",
  "Repair: smaller range": "תיקון: טווח קטן יותר",
  "Play a full repetition, or use Start and Finish for a static inspection. Check both hands, feet and the return.": "נגנו חזרה מלאה, או הציגו התחלה וסיום לבדיקה ללא תנועה. בדקו את שתי הידיים, כפות הרגליים והחזרה להתחלה.",
  "Before saving": "לפני השמירה",
  "Supports touch the intended body areas": "התמיכות נוגעות באזורי הגוף המתאימים",
  "Both hands and feet stay in contact": "שתי הידיים וכפות הרגליים שומרות על מגע",
  "Start and finish look correct": "ההתחלה והסיום נראים נכונים",
  "Return is smooth and matches the start": "החזרה חלקה ותואמת להתחלה",
  "The checklist helps your review; it does not lock saving. Highlight muscles only when you choose them.": "הרשימה עוזרת בבדיקה ואינה חוסמת שמירה. הדגישו שרירים רק לפי בחירתכם.",
  "For example, seated cable row": "למשל, חתירה בישיבה בכבל",
  "Name your private exercise": "שם לתרגיל הפרטי שלך",
  "This stays private. Muscles, classifications and instructions can be added later.": "התרגיל נשאר פרטי. אפשר להוסיף שרירים, סיווגים והוראות בהמשך.",
  "Saved private exercise": "תרגיל פרטי שנשמר",
  "Your exercise": "התרגיל שלך",
  "Your playable preview is above. Keep editing or add optional details.": "התצוגה הניתנת לניגון נמצאת למעלה. אפשר להמשיך לערוך או להוסיף פרטים אופציונליים.",
  "Row pull": "משיכת חתירה",
  "Arm closure": "סגירת ידיים",
  "Arm opening": "פתיחת ידיים",
  "Pulldown travel": "טווח המשיכה העליונה",
  "Bar height": "גובה המוט",
  "Sled extension": "יישור המזחלת",
  "Movement": "תנועה",
  "The seat supports the figure and both hands follow the pulldown bar.": "המושב תומך בדמות ושתי הידיים עוקבות אחר מוט המשיכה.",
  "Squat with planted feet. The bar stays on its guide rails.": "סקוואט עם כפות רגליים יציבות. המוט נשאר על המסילות.",
  "The back stays supported and both feet follow the sled.": "הגב נשאר נתמך ושתי כפות הרגליים עוקבות אחר המזחלת.",
  "Sit with feet on the footplates. Both hands follow the row handle toward the torso.": "ישיבה עם כפות הרגליים על המשטחים. שתי הידיים עוקבות אחר ידית החתירה לכיוון הגוף.",
  "The seat and back pad support the figure. Both hands follow the arms as they close in front of the chest.": "המושב ומשענת הגב תומכים בדמות. שתי הידיים עוקבות אחר זרועות המכונה בסגירה לפני החזה.",
  "Face the pad with your chest supported and feet planted. Open both arms outward, then return with control.": "פנו אל הכרית כשהחזה נתמך וכפות הרגליים יציבות. פתחו את שתי הידיים החוצה וחזרו בשליטה.",
  "Retry saving": "ניסיון שמירה נוסף",
  "Recovery copy on this device": "עותק לשחזור במכשיר זה",
  "Local recovery unavailable · save before leaving": "שחזור מקומי אינו זמין · שמרו לפני היציאה",
  "Sign in again": "כניסה מחדש",
  "Recover draft": "שחזור טיוטה",
  "An unfinished draft is available on this device": "טיוטה שלא הושלמה זמינה במכשיר זה",
  "Restore recovered draft": "שחזור הטיוטה המקומית",
  "Keep server version": "שמירת גרסת השרת",
  "Undo": "ביטול",
  "Redo": "ביצוע מחדש",
  "Recovery and shortcuts": "שחזור וקיצורי דרך",
  "Restore last saved": "שחזור השמירה האחרונה",
  "Restore last saved replaces the scene and name. Undo restores the current scene.": "שחזור השמירה האחרונה מחליף את הסצנה והשם. ביטול מחזיר את הסצנה הנוכחית.",
  "Use Tab to move between controls, arrows on sliders, and Escape to close equipment. Playback is always optional. Camera, grip and pose controls also have buttons.": "השתמשו ב־Tab למעבר בין פקדים, בחצים למחוון וב־Escape לסגירת בחירת הציוד. ניגון הוא תמיד אופציונלי. למצלמה, לאחיזה ולתנוחה יש גם כפתורים.",
  "Name your exercise before saving.": "יש לתת שם לתרגיל לפני השמירה.",
  "Offline · draft kept on this device": "אין חיבור · הטיוטה נשמרת במכשיר זה",
  "Reconnect, then Retry.": "התחברו מחדש ואז נסו שוב.",
  "Could not save · draft retained": "השמירה נכשלה · הטיוטה נשמרת",
  "Connected · ready to save": "מחובר · אפשר לשמור",
  "This draft has not saved and local recovery is unavailable. Leave and lose these edits?": "הטיוטה לא נשמרה ושחזור מקומי אינו זמין. לצאת ולאבד את השינויים האלה?",
  "Unsaved changes": "שינויים שלא נשמרו",
  "Check the frame time.": "בדקו את זמן התנוחה.",
  "Camera": "מצלמה",
  "Edit": "עריכה",
  "Preview controls": "פקדי תצוגה מקדימה",
  "Interaction mode": "מצב פעולה",
  "Drag to look around. Camera controls do not change your exercise.": "גררו כדי להביט מסביב. פקדי המצלמה אינם משנים את התרגיל.",
  "Select the body, a joint or equipment to edit. Use the labeled settings for precise changes.": "בחרו את הגוף, מפרק או ציוד לעריכה. השתמשו בפקדים המסומנים לשינויים מדויקים.",
  "Model view": "זווית תצוגת הדמות",
  "Front": "מלפנים",
  "Back view": "מאחור",
  "Three-quarter": "שלושת רבעי",
  "Side": "מהצד",
  "Camera actions": "פעולות מצלמה",
  "Zoom in": "קירוב",
  "Zoom out": "הרחקה",
  "Fit scene": "התאמת הסצנה למסך",
  "Reset view": "איפוס תצוגה",
  "Opposite side": "הצד הנגדי",
  "selected": "הבחירה",
  "Full screen": "מסך מלא",
  "Exit full screen": "יציאה ממסך מלא",
  "Fade equipment to inspect contacts": "החלשת נראות הציוד לבדיקת מגעים",
  "Equipment is faded only in this preview. Uncheck to restore it.": "נראות הציוד נחלשת רק בתצוגה זו. הסירו את הסימון להחזרתה.",
  "Loading body and equipment…": "טוען גוף וציוד…",
  "3D preview needs WebGL.": "תצוגת תלת־ממד דורשת WebGL.",
  "Could not load the 3D preview.": "טעינת תצוגת התלת־ממד נכשלה.",
  "You can keep editing below while the preview loads.": "אפשר להמשיך לערוך למטה בזמן טעינת התצוגה.",
  "Enable browser graphics acceleration or try another browser. The text summary and editing controls remain available.": "הפעילו האצה גרפית בדפדפן או נסו דפדפן אחר. תקציר הטקסט ופקדי העריכה נשארים זמינים.",
  "Check your connection, then retry. The text summary and editing controls remain available.": "בדקו את החיבור ונסו שוב. תקציר הטקסט ופקדי העריכה נשארים זמינים.",
  "Retry preview": "ניסיון טעינה נוסף",
  "Favorite": "מועדף",
  "Favorites": "מועדפים",
  "Choose equipment for your scene.": "בחרו ציוד לסצנה שלכם.",
  "Search equipment": "חיפוש ציוד",
  "Try cable, bench or dumbbell": "נסו כבל, ספסל או משקולת יד",
  "No matching equipment. Try cable, bench or hand weights.": "לא נמצא ציוד מתאים. נסו כבל, ספסל או משקולות יד.",
  "No 3D model yet. Choose another item.": "אין עדיין מודל תלת־ממד. בחרו פריט אחר.",
  "Favorites and recent choices are kept for this session. Browser storage is unavailable.": "מועדפים ובחירות אחרונות נשמרים להפעלה זו. אחסון הדפדפן אינו זמין.",
  "Recent equipment": "ציוד שנבחר לאחרונה",
  "Essentials": "ציוד בסיסי",
  "Favorite equipment": "ציוד מועדף",
  "Machines": "מכונות",
  "Weights": "משקולות",
  "Supports": "תמיכות",
  "Show all equipment": "הצגת כל הציוד",
  "Enter a valid number.": "הזינו מספר תקין.",
  "Arms": "ידיים",
  "Legs": "רגליים",
  "Torso": "גו",
  "torso": "גו",
  "Left": "שמאל",
  "Right": "ימין",
  "left": "שמאל",
  "right": "ימין",
  "both": "שני הצדדים",
  "Choose a body joint": "בחירת מפרק בגוף",
  "Body area": "אזור הגוף",
  "Body side": "צד הגוף",
  "shoulder": "כתף",
  "elbow": "מרפק",
  "wrist": "שורש כף היד",
  "hip": "ירך",
  "knee": "ברך",
  "ankle": "קרסול",
  "Muscle exploration": "חקר שרירים",
  "Find a body area or muscle": "חיפוש אזור בגוף או שריר",
  "Shoulders, upper arm, butt…": "כתפיים, זרוע, ישבן…",
  "Highlight": "הדגשה",
  "None": "ללא",
  "Muscle groups (both sides)": "קבוצות שרירים בשני הצדדים",
  "Individual muscles and structures": "שרירים ומבנים בודדים",
  "Show selected only": "הצגת הבחירה בלבד",
  "No matches. Try a body area such as shoulders, upper arm or butt, or a formal name such as gluteus. Your selected highlight stays selected.": "אין התאמות. נסו אזור כגון כתפיים, זרוע או ישבן, או שם מדעי כגון gluteus. ההדגשה שבחרתם נשמרת.",
  "Loading anatomy model…": "טוען מודל אנטומי…",
  "No muscles highlighted": "אין שרירים מודגשים",
  "No muscle highlight selected.": "לא נבחרה הדגשת שרירים.",
  "Retry the preview to explore anatomy.": "נסו לטעון את התצוגה מחדש לחקר האנטומיה.",
  "Shoulders (deltoids)": "כתפיים (deltoids)",
  "Rear shoulders (posterior deltoids)": "כתפיים אחוריות (posterior deltoids)",
  "Biceps": "שריר הזרוע הדו־ראשי",
  "Triceps — all heads": "שריר הזרוע התלת־ראשי, כל הראשים",
  "Traps (trapezius) — all parts": "טרפז (trapezius), כל החלקים",
  "Chest (pectoralis major)": "חזה (pectoralis major)",
  "Lats (latissimus dorsi)": "גב רחב (latissimus dorsi)",
  "Abdominals": "שרירי בטן",
  "Glutes": "שרירי ישבן",
  "Quadriceps": "שריר הירך הארבע־ראשי",
  "Hamstrings": "שרירי הירך האחוריים",
  "Calves": "שרירי השוק",
  "structure": "מבנה",
  "structures": "מבנים",
  "isolated": "מוצגים בנפרד",
  "highlighted": "מודגשים",
  "Workshop controls": "פקדי הסדנה",
  "Workshop tools": "כלי הסדנה",
  "Pose body": "התאמת תנוחת הגוף",
  "Leave machine": "עזיבת המכונה",
  "Stand up": "עמידה",
  "Restricts both shoulders to side-to-side movement across every pose. One Undo restores all previous poses.": "מגביל את שתי הכתפיים לתנועה לצדדים בכל התנוחות. ביטול אחד משחזר את כל התנוחות הקודמות.",
  "Frontal-plane lock": "נעילת תנועת כתפיים לצדדים",
  "Side-to-side shoulder movement only": "תנועת כתפיים לצדדים בלבד",
  "Sensitivity": "רגישות",
  "Movement sensitivity": "רגישות התנועה",
  "Save scene": "שמירת סצנה",
  "Save & add details": "שמירה והוספת פרטים",
  "Collapse preview": "כיווץ התצוגה המקדימה",
  "Show preview": "הצגת תצוגה מקדימה",
  "Previewing movement": "מציג תנועה",
  "Select the machine to move the figure": "בחרו את המכונה להזזת הדמות",
  "Drag a colored ring to rotate": "גררו טבעת צבעונית לסיבוב",
  "Drag an arrow to move": "גררו חץ להזזה",
  "Drag the figure or equipment to move it": "גררו את הדמות או הציוד להזזה",
  "use the palm controls": "השתמשו בפקדי כף היד",
  "drag a ring to pose": "גררו טבעת להתאמת התנוחה",
  "Playback controls": "פקדי ניגון",
  "Pause": "השהיה",
  "Play": "ניגון",
  "Preview speed": "מהירות תצוגה מקדימה",
  "Preview time": "זמן תצוגה מקדימה",
  "Editing pose": "תנוחה בעריכה",
  "Edit this moment": "עריכת רגע זה",
  "Previous pose": "התנוחה הקודמת",
  "Next pose": "התנוחה הבאה",
  "Animate movement": "הנפשת תנועה",
  "Optional": "אופציונלי",
  "Choose the pose to edit. Machine travel affects its moving parts; placement stays fixed.": "בחרו את התנוחה לעריכה. טווח המכונה משנה את חלקיה הנעים. המיקום נשאר קבוע.",
  "Scrub timeline": "בחירת זמן בציר הזמן",
  "Selected keyframe": "תנוחת מפתח נבחרת",
  "Selected:": "נבחר:",
  "Edit keyframe": "עריכת תנוחת מפתח",
  "Delete keyframe": "מחיקת תנוחת מפתח",
  "Add keyframe": "הוספת תנוחת מפתח",
  "Pose editing scope": "היקף עריכת התנוחה",
  "Edit this pose": "עריכת תנוחה זו",
  "Apply to all poses": "החלה על כל התנוחות",
  "Joint adjustments replace that joint across every pose in one Undo step.": "התאמת המפרק מחליפה אותו בכל התנוחות. ביטול אחד מחזיר את השינוי.",
  "Copy pose to": "העתקת תנוחה אל",
  "Copy pose destination": "יעד העתקת התנוחה",
  "Copy to chosen pose": "העתקה לתנוחה שנבחרה",
  "Copy to all poses": "העתקה לכל התנוחות",
  "Mirror sides": "החלפת הצדדים כמראה",
  "Match loop end to start": "התאמת סוף הלולאה להתחלה",
  "Frame time · seconds": "זמן התנוחה · שניות",
  "Keyframe time seconds": "זמן תנוחת מפתח בשניות",
  "Update time": "עדכון זמן",
  "Start stays at 0; End stays at Duration. Deleting either uses the next surviving pose. Keep at least two frames.": "ההתחלה נשארת באפס והסוף במשך הכולל. מחיקה משתמשת בתנוחה הסמוכה שנותרה. יש לשמור לפחות שתי תנוחות.",
  "Edit the selected pose or equipment controls. Use Undo to restore changes.": "ערכו את התנוחה שנבחרה או את פקדי הציוד. השתמשו בביטול לשחזור שינויים.",
  "Timeline settings": "הגדרות ציר זמן",
  "Duration": "משך",
  "In your scene": "בסצנה שלך",
  "Scene objects": "פריטים בסצנה",
  "Anatomical figure": "דמות אנטומית",
  "Selected item": "הפריט שנבחר",
  "Regular · chest fly": "רגיל · פרפר לחזה",
  "Reverse · rear delt fly": "הפוך · פרפר לכתף אחורית",
  "Pulldown grip": "אחיזה במשיכה עליונה",
  "Supinated · palms toward you": "אחיזה תחתית · כפות ידיים אליך",
  "Pronated · palms away from you": "אחיזה עילית · כפות ידיים הרחק ממך",
  "Pronated · frontal pulldown": "אחיזה עילית · משיכה מלפנים",
  "Stop using machine": "הפסקת שימוש במכונה",
  "Use this machine": "שימוש במכונה זו",
  "Machine travel percent": "טווח המכונה באחוזים",
  "Animate selected item creates editable moments for moving parts. The frame stays in place.": "הנפשת הפריט שנבחר יוצרת רגעים לעריכת חלקיו הנעים. המסגרת נשארת במקום.",
  "Stop using machine to pose freely": "הפסקת שימוש במכונה להתאמת תנוחה חופשית",
  "Release weight to pose arm": "שחרור המשקולת להתאמת היד",
  "Select machine": "בחירת מכונה",
  "Select held weight": "בחירת המשקולת המוחזקת",
  "The machine controls contact. Select the machine to edit its travel, or stop using it to pose freely.": "המכונה שולטת במגע. בחרו אותה לעריכת הטווח, או הפסיקו להשתמש בה להתאמת תנוחה חופשית.",
  "These joint controls are paused while the weight is held.": "פקדי המפרק האלה מושבתים כל עוד המשקולת מוחזקת.",
  "Turn the palm, bend the wrist, or tilt it sideways.": "סובבו את כף היד, כופפו את שורש כף היד או הטו אותו לצדדים.",
  "0° is straight. Positive bends the knee backward; extension is limited to 5°.": "אפס מעלות הוא יישור. ערך חיובי מכופף את הברך לאחור. יישור מעבר לכך מוגבל לחמש מעלות.",
  "Raise or point the toes, turn the foot, or tilt it sideways.": "הרימו או מתחו את האצבעות, סובבו את כף הרגל או הטו אותה לצדדים.",
  "Drag a rotation ring, or use these sliders.": "גררו טבעת סיבוב, או השתמשו במחוונים האלה.",
  "Palm up": "כף יד למעלה",
  "Neutral": "ניטרלי",
  "Palm down": "כף יד למטה",
  "Supinated": "כף יד פונה למעלה",
  "Pronated": "כף יד פונה למטה",
  "Neutral grip": "אחיזה ניטרלית",
  "Frontal-plane lock applies to both shoulders across all keyframes. Edit side-to-side motion below.": "נעילת התנועה לצדדים חלה על שתי הכתפיים בכל תנוחות המפתח. ערכו תנועה לצדדים למטה.",
  "Palm turn": "סיבוב כף יד",
  "Wrist bend": "כיפוף שורש כף היד",
  "Wrist tilt": "הטיית שורש כף היד",
  "Toes up / down": "אצבעות למעלה / למטה",
  "Foot turn": "סיבוב כף הרגל",
  "Foot tilt": "הטיית כף הרגל",
  "Bend": "כיפוף",
  "Turn": "סיבוב",
  "Side to side": "מצד לצד",
  "Reset joint": "איפוס מפרק",
  "Placement is locked while editing travel. Stop animation to reposition the machine.": "המיקום נעול בזמן עריכת הטווח. הפסיקו את ההנפשה לשינוי מיקום המכונה.",
  "Move": "הזזה",
  "Rotate": "סיבוב",
  "Up": "למעלה",
  "Down": "למטה",
  "Stop animation and edit placement": "הפסקת הנפשה ועריכת מיקום",
  "Animate selected item": "הנפשת הפריט שנבחר",
  "Static placement. Changes apply to the whole scene.": "מיקום קבוע. השינויים חלים על כל הסצנה.",
  "Bench pad angle · degrees": "זווית משענת הספסל · מעלות",
  "Bench pad angle": "זווית משענת הספסל",
  "Bench pad angle degrees": "זווית משענת הספסל במעלות",
  "0° is flat. Adjusts the pad and support frame for the whole scene.": "אפס מעלות הוא מצב שטוח. מתאים את המשענת והמסגרת לכל הסצנה.",
  "Sit on this bench": "ישיבה על ספסל זה",
  "The figure follows the bench. Stand up to move the figure freely.": "הדמות עוקבת אחר הספסל. עברו לעמידה כדי להזיז אותה בחופשיות.",
  "Attach cuff": "חיבור רצועה",
  "Hold cable handle": "אחיזה בידית הכבל",
  "Hold this weight": "אחיזה במשקולת זו",
  "Held with both hands": "מוחזק בשתי הידיים",
  "The cuff follows the arm. Pose the shoulder and elbow freely.": "הרצועה עוקבת אחר היד. אפשר להתאים את הכתף והמרפק בחופשיות.",
  "The cable follows the hand as you pose the body.": "הכבל עוקב אחר היד כשמשנים את תנוחת הגוף.",
  "Move the weight to move the arms with it.": "הזיזו את המשקולת כדי להזיז את הידיים יחד איתה.",
  "Attachment outside reach. Bring the hands closer together or adjust the arm poses.": "האביזר מחוץ לטווח ההגעה. קרבו את הידיים זו לזו או התאימו את תנוחתן.",
  "Outside the locked elbow’s reach. Move the weight along the curl arc, or unlock the elbow.": "מחוץ לטווח ההגעה של המרפק הנעול. הזיזו את המשקולת בקשת הכיפוף או שחררו את נעילת המרפק.",
  "Too far to reach. Move the weight closer to the figure.": "רחוק מדי להגעה. קרבו את המשקולת לדמות.",
  "Release": "שחרור",
  "Lock an elbow at its current position relative to the figure. Position the arm on the pad first, then keep the weight within reach.": "נעלו מרפק במיקומו ביחס לדמות. תחילה הניחו את היד על הכרית, ואז שמרו על המשקולת בטווח ההגעה.",
  "Lock": "נעילה",
  "Unlock": "שחרור נעילה",
  "Align pulley beside shoulder": "יישור הגלגלת לצד הכתף",
  "Follows the shoulder when the figure or bench moves. Pulley height stays adjustable.": "עוקב אחר הכתף כשהדמות או הספסל זזים. עדיין אפשר לשנות את גובה הגלגלת.",
  "Use manual placement": "מיקום ידני",
  "Cable attachment": "אביזר כבל",
  "Cuff placement": "מיקום הרצועה",
  "At wrist": "בשורש כף היד",
  "Above elbow": "מעל המרפק",
  "Face away from bench": "פנים הרחק מהספסל",
  "Face left": "פנים לשמאל",
  "Face right": "פנים לימין",
  "Face bench · chest supported": "פנים לספסל · חזה נתמך",
  "D handle": "ידית D",
  "Rope": "חבל",
  "Straight bar": "מוט ישר",
  "Angled bar": "מוט זוויתי",
  "V bar": "מוט V",
  "Cuff": "רצועה",
  "Pulley height · meters": "גובה הגלגלת · מטרים",
  "Adjust pulley height": "התאמת גובה הגלגלת",
  "Pulley height meters": "גובה הגלגלת במטרים",
  "Low pulley": "גלגלת נמוכה",
  "Middle pulley": "גלגלת באמצע",
  "High pulley": "גלגלת גבוהה",
  "Above head": "מעל הראש",
  "Remove item": "הסרת פריט",
  "Remove demo equipment": "הסרת ציוד הדגמה",
  "Advanced settings": "הגדרות מתקדמות",
  "Snap to grid": "הצמדה לרשת",
  "3D arrows": "חצי תלת־ממד",
  "Resize": "שינוי גודל",
  "Item name": "שם הפריט",
  "Duplicate": "שכפול",
  "Movement setup": "הגדרת תנועה",
  "Free posing": "התאמת תנוחה חופשית",
  "Squat — feet planted": "סקוואט עם כפות רגליים יציבות",
  "Hip hinge — feet planted": "כיפוף בירך עם כפות רגליים יציבות",
  "Bent-over row": "חתירה בהטיית גוף",
  "Stationary lunge": "מכרע במקום",
  "Incline bench press": "לחיצה על ספסל משופע",
  "Seated biceps curl": "כפיפת מרפקים בישיבה",
  "Incline dumbbell curl": "כפיפת מרפקים עם משקולות על ספסל משופע",
  "Legacy demo equipment": "ציוד הדגמה קודם",
  "Add equipment → drag to position → save and add details": "הוסיפו ציוד, מקמו אותו, שמרו והוסיפו פרטים",
  "Drag empty space to turn the camera · scroll to zoom": "גררו באזור ריק לסיבוב המצלמה · גללו לקירוב והרחקה",
  "Position": "מיקום",
  "Rotation": "סיבוב",
  "Scale": "קנה מידה",
  "meters": "מטרים",
  "degrees": "מעלות",
  "seconds": "שניות",
  "percent": "אחוזים",
  " · meters": " · מטרים",
  " · degrees": " · מעלות",
  " · demo equipment": " · ציוד הדגמה",
  "Palms toward each other": "כפות ידיים זו אל זו",
  "Palms outward": "כפות ידיים החוצה",
  "Palms toward you": "כפות ידיים אליך",
  "Palms away from you": "כפות ידיים ממך והלאה",
  "Keep elbows beside the body": "מרפקים לצד הגוף",
  "Arms at shoulder height": "ידיים בגובה הכתפיים",
  "Palm choice": "כיוון כפות הידיים",
  "Elbow path": "מסלול המרפקים",
  "Grip choices": "אפשרויות אחיזה",
  "Shorten the start or finish range until the hand touches the handle.": "קצרו את טווח ההתחלה או הסיום עד שהיד נוגעת בידית.",
  "Shorten the range, change the palm choice, or try the other elbow path.": "קצרו את הטווח, שנו את כיוון כף היד או נסו את מסלול המרפק האחר.",
  "Shorten the range or try the other elbow path.": "קצרו את הטווח או נסו את מסלול המרפק האחר.",
  "Favorite {equipment}": "הוספת {equipment} למועדפים",
  "{count} equipment choices": "{count} אפשרויות ציוד",
  "Decrease {label} by {increment}": "הפחתת {label} ב־{increment}",
  "Increase {label} by {increment}": "הגדלת {label} ב־{increment}",
  "Enter a number from {min} to {max}.": "הזינו מספר בין {min} ל־{max}.",
  "Enter a number of {min} or more.": "הזינו מספר {min} או יותר.",
  "Enter a number of {max} or less.": "הזינו מספר {max} או פחות.",
  "Start {movement} percent": "התחלה {movement} באחוזים",
  "Finish {movement} percent": "סיום {movement} באחוזים",
  "Position {axis} meters": "מיקום {axis} במטרים",
  "Rotation {axis} degrees": "סיבוב {axis} במעלות",
  "Focus {selection}": "מיקוד על {selection}",
  "{name} start to finish": "{name} מהתחלה לסיום",
  "{side} shoulder": "כתף {side}",
  "{side} elbow": "מרפק {side}",
  "{side} wrist": "שורש כף יד {side}",
  "{side} hip": "ירך {side}",
  "{side} knee": "ברך {side}",
  "{side} ankle": "קרסול {side}",
  "Step {number}: {step}": "שלב {number}: {step}",
  "Saved at {time} · Private": "נשמר ב־{time} · פרטי",
  "Restore the scene and name from {time}. Your last server save stays available.": "שחזור הסצנה והשם מ־{time}. השמירה האחרונה בשרת נשארת זמינה.",
  "Removed {item} — Undo restores it.": "{item} הוסר. ביטול מחזיר אותו.",
  "{item} controls contact": "{item} שולט במגע",
  "{item} controls this arm": "{item} שולט ביד זו",
  "Preview time {preview} · Editing pose {pose}": "זמן תצוגה {preview} · תנוחה בעריכה {pose}",
  "Speed changes this preview only. Saved duration remains {duration}.": "המהירות משנה רק תצוגה זו. המשך שנשמר הוא {duration}.",
  "Keyframe {number}": "תנוחת מפתח {number}",
  "Joint adjustments affect pose {number} only.": "התאמות המפרק חלות רק על תנוחה {number}.",
  "Pose {number} · {time}": "תנוחה {number} · {time}",
  "{item} keeps the hands and feet in contact. Select the machine to change travel.": "{item} שומר על מגע הידיים וכפות הרגליים. בחרו את המכונה לשינוי הטווח.",
  "{item} controls this arm. Move the weight to pose the arm; wrist controls remain available.": "{item} שולט ביד זו. הזיזו את המשקולת להתאמת היד. פקדי שורש כף היד נשארים זמינים.",
  "Editing {time}.": "עריכה ב־{time}.",
  "Editing {time}. Changes affect this moment only.": "עריכה ב־{time}. השינויים חלים רק על רגע זה.",
  "The figure follows {item}. Select the machine to move it or change travel.": "הדמות עוקבת אחר {item}. בחרו את המכונה להזזה או לשינוי הטווח.",
  "Place {item} using the buttons or coordinates.": "מקמו את {item} בעזרת הכפתורים או הקואורדינטות.",
  "this item": "הפריט הזה",
  "the figure": "הדמות",
  "Hold with {hand}": "אחיזה באמצעות {hand}",
  "left hand": "יד שמאל",
  "right hand": "יד ימין",
  "both hands": "שתי הידיים",
  "Cuff {side} arm": "חיבור רצועה ליד {side}",
  "Cuffed {side} {position}": "רצועה בצד {side}, {position}",
  "above elbow": "מעל המרפק",
  "Held with {side} hand": "מוחזק ביד {side}",
  "Beside {side} shoulder": "לצד כתף {side}",
  "{groups} groups · {individual} individual structures found": "נמצאו {groups} קבוצות · {individual} מבנים בודדים",
  "{count} muscle structures · separate sides and heads": "{count} מבני שרירים · צדדים וראשים נפרדים",
  "{label} (selected)": "{label} (נבחר)",
  "Selected highlight: {label}.": "הדגשה נבחרת: {label}.",
  "Anatomy preview unavailable. {selection} Retry the preview to explore anatomy.": "תצוגת אנטומיה אינה זמינה. {selection} נסו לטעון את התצוגה מחדש לחקר האנטומיה.",
  "{label} · {count} {structure} {state}": "{label} · {count} {structure} {state}",
  "{side} hand cannot reach the handle.": "יד {side} אינה מגיעה לידית.",
  "{side} wrist bends {angle}° to keep hold.": "שורש כף יד {side} מתכופף {angle}° כדי לשמור על האחיזה.",
  "{side} elbow leaves the chosen path to reach the handle.": "מרפק {side} יוצא מהמסלול שנבחר כדי להגיע לידית.",
};

const parameterPattern = /\{([a-zA-Z]+)\}/g;
const templateEntries = Object.entries(workshopHebrew).filter(([key]) => key.includes("{")).map(([key, translation]) => {
  const names: string[] = [];
  const escaped = key.replace(/[.*+?^$()|[\]\\]/g, "\\$&").replace(parameterPattern, (_, name: string) => { names.push(name); return "(.+?)"; });
  return { names, translation, pattern: new RegExp(`^${escaped}$`, "i") };
});

export function workshopDirection(language: WorkshopLanguage): "rtl" | "ltr" {
  return language === "he" ? "rtl" : "ltr";
}

export function parseLocalizedWorkshopNumber(text: string, min?: number, max?: number): number | null {
  return parseWorkshopNumber(text.replace(/[\u200e\u200f\u061c]/g, ""), min, max);
}

export function createWorkshopLanguage(language: WorkshopLanguage) {
  const locale = language === "he" ? "he-IL" : "en-US";
  const formatNumber = (value: number, options?: Intl.NumberFormatOptions) => new Intl.NumberFormat(locale, options).format(value);
  const t = (text: string, params?: WorkshopTranslationParams): string => {
    let translated = language === "he" ? workshopHebrew[text] : text;
    let values = params;
    if (language === "he" && translated === undefined) {
      const trimmed = text.trim();
      translated = workshopHebrew[trimmed];
      if (translated) return text.replace(trimmed, translated);
      for (const template of templateEntries) {
        const match = trimmed.match(template.pattern);
        if (!match) continue;
        translated = template.translation;
        values = Object.fromEntries(template.names.map((name, index) => [name, match[index + 1]]));
        break;
      }
    }
    return (translated ?? text).replace(parameterPattern, (placeholder, name: string) => {
      const value = values?.[name];
      if (value === undefined) return placeholder;
      return typeof value === "number" ? formatNumber(value) : language === "he" ? workshopHebrew[value] ?? workshopHebrew[value.toLowerCase()] ?? value : value;
    });
  };
  return { language, t, formatNumber };
}
