import { cleanupLocalFixture } from "../helpers/local-fixtures";
import { setWorkshopLanguage, selectWorkshopObject, expandWorkshopControls, openWorkshopRecovery } from "./workshop-menu.helpers";
import { randomUUID } from "node:crypto";
import { mkdirSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";
import { expect, test } from "@playwright/test";
import { createStudioObject } from "../../src/lib/motion/studio";
import { blankWorkshopScene, identityTransform } from "../../src/lib/motion/workshop";

test.use({ launchOptions: { args: ["--use-gl=angle", "--use-angle=swiftshader"] } });
test.beforeEach(async ({ page }) => page.setDefaultTimeout(60_000));

test("workshop tools are directly accessible without scrolling through unrelated controls", async ({ page }) => {
  test.setTimeout(120_000); page.setDefaultTimeout(60_000);
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
  if (!["localhost", "127.0.0.1"].includes(new URL(url).hostname)) throw Error("Local fixtures required");
  const admin = createClient(url, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false } });
  const email = `tools-${randomUUID()}@example.test`, password = "WorkshopTools2026!";
  const account = await admin.auth.admin.createUser({ email, password, email_confirm: true });
  if (account.error) throw account.error;

  try {
    const owner = createClient(url, process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!, { auth: { persistSession: false } });
    await owner.auth.signInWithPassword({ email, password });
    const errors: string[] = [];
    page.on("pageerror", error => errors.push(error.message));
    page.on("console", message => { if (message.type() === "error" && message.text().includes('unique "key"')) errors.push(message.text()); });
    const bench = { ...createStudioObject("bench", randomUUID(), 0), ...identityTransform };
    const cable = createStudioObject("cable-machine", randomUUID(), 1);
    const created = await owner.rpc("save_workshop_draft", { p_scene: { ...blankWorkshopScene,
      studio: { body: identityTransform, objects: [bench, cable], seating: { benchId: bench.id, facing: "front" } } }, p_name: "Workshop navigation fixture" });
    if (created.error) throw created.error;
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.goto("/sign-in");
    await page.getByLabel("Email", { exact: true }).fill(email); await page.getByLabel("Password", { exact: true }).fill(password);
    await page.getByRole("button", { name: "Sign in", exact: true }).click(); await expect(page).toHaveURL(/\/dashboard$/);
    await page.goto(`/my-exercises/${created.data}/workshop`);
    await expect(page.locator('[data-anatomy-state="ready"]')).toBeVisible({ timeout: 60_000 });
    await page.setViewportSize({ width: 1024, height: 900 });
    await expect.poll(async () => {
      const sidebar = (await page.getByRole("region", { name: "Quick create", exact: true }).boundingBox())!;
      const canvas = (await page.locator("canvas").boundingBox())!;
      return sidebar.x > canvas.x + canvas.width;
    }).toBe(true);
    const quickBounds = (await page.getByRole("region", { name: "Quick create", exact: true }).boundingBox())!;
    const canvasBounds = (await page.locator("canvas").boundingBox())!;
    expect(canvasBounds.height).toBeGreaterThan(450);
    expect((await page.locator('[data-workshop="studio"]').boundingBox())!.y).toBe(0);
    await page.getByRole("button", { name: "Full screen", exact: true }).click();
    await expect.poll(() => page.locator('[data-workshop="studio"]').evaluate(element => document.fullscreenElement === element)).toBe(true);
    await page.setViewportSize({ width: 1280, height: 900 });
    // Entering fullscreen resizes a real browser; it must stay open afterward.
    await page.waitForTimeout(750);
    expect(await page.locator('[data-workshop="studio"]').evaluate(element => document.fullscreenElement === element)).toBe(true);
    mkdirSync(".local-artifacts/workshop/tools", { recursive: true });
    await page.screenshot({ path: ".local-artifacts/workshop/tools/fullscreen.png" });
    await page.getByRole("button", { name: "Exit full screen", exact: true }).click();
    await page.setViewportSize({ width: 1024, height: 900 });
    await expect.poll(() => page.evaluate(() => document.fullscreenElement === null)).toBe(true);
    // Embedded browsers can leave the Fullscreen API promise pending indefinitely.
    const fullscreenMethod = await page.evaluateHandle(() => Element.prototype.requestFullscreen);
    await page.evaluate(() => {
      Element.prototype.requestFullscreen = () => new Promise<void>(() => {});
    });
    await page.getByRole("button", { name: "Full screen", exact: true }).click();
    await expect(page.getByRole("alert").filter({ hasText: "Use F11" })).toBeVisible({ timeout: 5000 });
    await expect(page.getByRole("button", { name: "Full screen", exact: true })).toBeEnabled();
    await page.evaluate(() => { Element.prototype.requestFullscreen = () => Promise.reject(new TypeError("Blocked")); });
    await page.getByRole("button", { name: "Full screen", exact: true }).click();
    await expect(page.getByRole("alert").filter({ hasText: "Use F11" })).toBeVisible();
    await page.evaluate(method => { Element.prototype.requestFullscreen = method; }, fullscreenMethod);
    await fullscreenMethod.dispose();
    await page.getByRole("button", { name: "Full screen", exact: true }).click();
    await expect(page.getByRole("button", { name: "Exit full screen", exact: true })).toBeVisible();
    await expect(page.getByRole("alert").filter({ hasText: "Use F11" })).toHaveCount(0);
    await page.getByRole("button", { name: "Exit full screen", exact: true }).click();
    expect(quickBounds.x).toBeGreaterThan(canvasBounds.x + canvasBounds.width);
    await openWorkshopRecovery(page);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.getByText("Recovery and shortcuts", { exact: true }).click();
    await page.locator("[data-workshop-menu] > summary").click();
    await page.setViewportSize({ width: 1440, height: 1000 });
    const tools = page.getByRole("tablist", { name: "Workshop tools", exact: true });
    const open = async (name: string) => {
      const tab = tools.getByRole("tab", { name, exact: true }); await expect(tab).toBeInViewport();
      await tab.click(); await expect(tab).toHaveAttribute("aria-selected", "true");
    };
    await page.getByRole("button", { name: "Advanced editing", exact: true }).click();
    await expect(tools).toBeVisible({ timeout: 5000 });
    await open("Equipment");
    await tools.getByRole("tab", { name: "Equipment", exact: true }).press("ArrowRight");
    await expect(tools.getByRole("tab", { name: "Position", exact: true })).toBeFocused();
    await expect(tools.getByRole("tab", { name: "Position", exact: true })).toHaveAttribute("aria-selected", "true");
    await tools.getByRole("tab", { name: "Position", exact: true }).press("Home");
    await expect(tools.getByRole("tab", { name: "Equipment", exact: true })).toBeFocused();
    await selectWorkshopObject(page, "Adjustable bench");
    await expect(page.getByRole("button", { name: "Lie face up", exact: true })).toBeInViewport();
    await page.getByRole("button", { name: "Lie face up", exact: true }).click();
    await open("Position");
    await expect(page.getByLabel("Position X meters", { exact: true })).not.toBeVisible();
    await expandWorkshopControls(page, "Precise placement");
    await expect(page.getByLabel("Position X meters", { exact: true })).toBeInViewport();
    await expect(page.getByRole("button", { name: "Lie face up", exact: true })).not.toBeVisible();
    await open("Equipment"); await selectWorkshopObject(page, "Cable machine");
    await expect(page.getByRole("button", { name: "Hold with right hand", exact: true })).toBeInViewport();
    await page.getByRole("button", { name: "Hold with right hand", exact: true }).click();
    await open("Pose"); await page.getByLabel("Body joint", { exact: true }).selectOption("left-elbow");
    await expect(page.getByRole("textbox", { name: "Bend Left elbow degrees", exact: true })).toBeInViewport();
    await page.getByRole("textbox", { name: "Bend Left elbow degrees", exact: true }).fill("70");
    await page.getByRole("textbox", { name: "Bend Left elbow degrees", exact: true }).press("Enter");
    await page.getByLabel("Editing pose", { exact: true }).selectOption("1");
    await expect(page.getByRole("textbox", { name: "Bend Left elbow degrees", exact: true })).toHaveValue("0");
    await page.getByLabel("Editing pose", { exact: true }).selectOption("0");
    await expect(page.getByRole("textbox", { name: "Bend Left elbow degrees", exact: true })).toHaveValue("70");
    await open("Timeline");
    await expect(page.getByRole("button", { name: "Add keyframe", exact: true })).toBeInViewport();
    await open("View"); await expect(page.getByLabel("Highlight", { exact: true })).toBeVisible();
    await page.getByLabel("Highlight", { exact: true }).selectOption("group:biceps");
    await open("Setups"); await expect(page.getByLabel("Setup name", { exact: true })).toBeInViewport();
    await page.getByLabel("Setup name", { exact: true }).fill("My bench and cable");
    await page.getByRole("button", { name: "Save equipment setup", exact: true }).click();
    await open("Contacts");
    await page.getByLabel("Selected equipment", { exact: true }).selectOption(bench.id);
    await expect(page.getByRole("button", { name: "Lie face up", exact: true })).toHaveAttribute("aria-pressed", "true");
    await page.getByRole("button", { name: "Save", exact: true }).click();
    await expect(page.getByText(/Saved at.*Private/)).toBeVisible();
    const saved = await owner.from("private_exercises").select("content_id").eq("id", created.data).single();
    const stored = await owner.from("exercise_scenes").select("studio_layout").eq("content_id", saved.data!.content_id).single();
    expect(stored.data?.studio_layout).toMatchObject({ seating: { benchId: bench.id, facing: "supine" }, presentation: { highlight: "group:biceps" } });
    mkdirSync(".local-artifacts/workshop/tools", { recursive: true });
    await page.screenshot({ path: ".local-artifacts/workshop/tools/desktop.png" });
    const preview = (await page.locator("canvas").boundingBox())!;
    expect(preview.height).toBeGreaterThan(550);
    expect(preview.y + preview.height).toBeLessThan(1000);
    await page.setViewportSize({ width: 390, height: 844 });
    await tools.scrollIntoViewIfNeeded();
    await page.screenshot({ path: ".local-artifacts/workshop/tools/mobile-before-contacts.png" });
    expect(await page.locator('[data-workshop="studio"]').evaluate(element => element.clientHeight)).toBe(844);
    await open("Contacts");
    await page.getByRole("button", { name: "Lie face down", exact: true }).click();
    await expect(page.getByRole("button", { name: "Lie face down", exact: true })).toHaveAttribute("aria-pressed", "true");
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: ".local-artifacts/workshop/tools/mobile.png" });
    await setWorkshopLanguage(page, "he");
    const hebrewTools = page.getByRole("tablist", { name: "כלי הסדנה", exact: true });
    await expect(hebrewTools).toBeVisible();
    await hebrewTools.getByRole("tab").first().press("ArrowLeft");
    await expect(hebrewTools.getByRole("tab").nth(1)).toBeFocused();
    await expect(hebrewTools.getByRole("tab").nth(1)).toHaveAttribute("aria-selected", "true");
    expect(errors).toEqual([]);
  } finally { await cleanupLocalFixture({ admin, userId: account.data.user.id, email, password }); }
});
