import { setWorkshopMode, openWorkshopMenu } from "./workshop-menu.helpers";
import { randomUUID } from "node:crypto";
import { mkdirSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";
import { expect, test } from "@playwright/test";
import { createQuickScene } from "../../src/lib/motion/quick-create";

test.use({ launchOptions: { args: ["--use-gl=angle", "--use-angle=swiftshader"] } });
test.beforeEach(async ({ page }) => page.setDefaultTimeout(15_000));

test("workshop history, inspector, focus, comparison and personal setups", async ({ page }) => {
  test.setTimeout(180_000);
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
  if (!["127.0.0.1", "localhost"].includes(new URL(url).hostname)) throw Error("Local fixtures required");
  const admin = createClient(url, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false } });
  const email = `improvements-${randomUUID()}@example.test`, password = "WorkshopImprove2026!";
  const account = await admin.auth.admin.createUser({ email, password, email_confirm: true });
  if (account.error) throw account.error;
  const owner = createClient(url, process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!, { auth: { persistSession: false } });
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  try {
    await owner.auth.signInWithPassword({ email, password });
    const initial = createQuickScene("cable-row-machine");
    initial.studio!.presentation = { ...initial.studio!.presentation!, isolate: true, highlight: "group:lats" };
    const created = await owner.rpc("save_workshop_draft", { p_scene: initial, p_name: "Improvement fixture" });
    if (created.error) throw created.error;
    await page.setViewportSize({ width: 1440, height: 1100 });
    await page.goto("/sign-in");
    await page.getByLabel("Email", { exact: true }).fill(email);
    await page.getByLabel("Password", { exact: true }).fill(password);
    await page.getByRole("button", { name: "Sign in", exact: true }).click();
    await expect(page).toHaveURL(/\/dashboard$/);
    await page.goto(`/my-exercises/${created.data}/workshop`);
    await expect(page.locator('[data-anatomy-state="ready"]')).toBeVisible({ timeout: 60_000 });
    await setWorkshopMode(page, "advanced");
    await page.getByLabel("Selected equipment", { exact: true }).selectOption({ label: "Cable row" });
    const selected = page.getByRole("region", { name: "Selected item", exact: true });
    await page.getByRole("tab", { name: "Position", exact: true }).click();
    await expect(selected.getByText("Placement", { exact: true })).toBeVisible();
    await page.getByRole("tab", { name: "Contacts", exact: true }).click();
    await expect(selected.getByText("Contact", { exact: true })).toBeVisible();
    await page.getByRole("tab", { name: "Timeline", exact: true }).click();
    await expect(page.getByText("Equipment movement", { exact: true })).toBeVisible();
    const slider = page.getByRole("slider", { name: "Row pull", exact: true });
    const before = await slider.inputValue();
    await slider.focus();
    await page.keyboard.down("ArrowRight");
    await page.keyboard.down("ArrowRight");
    await page.keyboard.down("ArrowRight");
    await page.keyboard.up("ArrowRight");
    const changed = await slider.inputValue();
    expect(changed).not.toBe(before);
    await page.getByRole("button", { name: "Undo", exact: true }).first().click();
    await expect(slider).toHaveValue(before);
    await page.getByRole("button", { name: "Redo", exact: true }).first().click();
    await expect(slider).toHaveValue(changed);
    await slider.scrollIntoViewIfNeeded();
    const track = (await slider.boundingBox())!;
    await page.mouse.move(track.x + track.width * .4, track.y + track.height / 2);
    await page.mouse.down();
    await page.mouse.move(track.x + track.width * .7, track.y + track.height / 2, { steps: 10 });
    await page.mouse.up();
    expect(await slider.inputValue()).not.toBe(changed);
    await page.getByRole("button", { name: "Undo", exact: true }).first().click();
    await expect(slider).toHaveValue(changed);
    await page.getByText("Edit history", { exact: true }).click();
    await expect(page.getByRole("region", { name: "Edit history" })).toContainText("Change Cable row movement");
    await openWorkshopMenu(page);
    await page.getByRole("button", { name: "Focus mode", exact: true }).click();
    await expect(page.locator('[data-workshop="studio"]')).toHaveAttribute("data-focus-mode", "true");
    await expect(page.getByRole("button", { name: "Save", exact: true })).toBeVisible();
    await expect(page.getByRole("button", { name: "Play", exact: true })).toBeInViewport();
    mkdirSync(".local-artifacts/workshop/improvements", { recursive: true });
    await page.screenshot({ path: ".local-artifacts/workshop/improvements/focus.png" });
    await page.getByRole("tab", { name: "View", exact: true }).click();
    await page.getByRole("button", { name: "Compare start and finish", exact: true }).click();
    await expect(page.getByRole("region", { name: "Start pose comparison" })).toBeVisible();
    await expect(page.getByRole("region", { name: "Finish pose comparison" })).toBeVisible();
    const startView = page.getByRole("region", { name: "Start pose comparison" });
    const finishView = page.getByRole("region", { name: "Finish pose comparison" });
    await expect(startView.locator('[data-anatomy-state="ready"]')).toBeVisible({ timeout: 60_000 });
    await expect(finishView.locator('[data-anatomy-state="ready"]')).toBeVisible({ timeout: 60_000 });
    await expect(startView.locator("[data-isolated]")).toHaveAttribute("data-isolated", "false");
    await expect(finishView.locator("[data-isolated]")).toHaveAttribute("data-isolated", "false");
    const startBeforePan = await startView.locator("canvas").screenshot();
    const bounds = (await finishView.locator("canvas").boundingBox())!;
    await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);
    await page.mouse.down({ button: "right" });
    await page.mouse.move(bounds.x + bounds.width / 2 + 50, bounds.y + bounds.height / 2 + 20, { steps: 8 });
    await page.mouse.up({ button: "right" });
    expect((await startView.locator("canvas").screenshot()).equals(startBeforePan)).toBe(false);
    await page.screenshot({ path: ".local-artifacts/workshop/improvements/comparison.png" });
    await page.getByRole("button", { name: "Close comparison", exact: true }).click();
    await openWorkshopMenu(page);
    await page.getByRole("button", { name: "Exit focus mode", exact: true }).click();
    await page.getByRole("tab", { name: "Timeline", exact: true }).click();
    await expect(page.getByRole("button", { name: /^Finish ·/ })).toBeVisible();
    await expect(page.getByRole("button", { name: /^Return ·/ })).toBeVisible();
    await page.getByRole("tab", { name: "Setups", exact: true }).click();
    await page.getByLabel("Setup name", { exact: true }).fill("My row setup");
    await page.getByRole("button", { name: "Save equipment setup", exact: true }).click();
    await expect(page.getByRole("button", { name: "My row setup", exact: true })).toBeVisible();
    await page.getByRole("button", { name: "My row setup", exact: true }).click();
    await page.getByLabel("Selected equipment", { exact: true }).selectOption({ label: "Cable row" });
    await page.getByRole("tab", { name: "Timeline", exact: true }).click();
    await expect(page.getByRole("button", { name: "Animate selected item", exact: true })).toBeVisible();
    await page.getByRole("button", { name: "Undo", exact: true }).first().click();
    await expect(page.getByRole("button", { name: "Stop animation and edit placement", exact: true })).toBeVisible();
    await page.locator('[data-workshop-preview]').evaluate(element => { element.scrollTop = 0; });
    await page.getByRole("tab", { name: "View", exact: true }).click();
    await page.getByRole("button", { name: "Compare start and finish", exact: true }).scrollIntoViewIfNeeded();
    await page.screenshot({ path: ".local-artifacts/workshop/improvements/desktop.png", fullPage: true });
    await page.reload();
    await setWorkshopMode(page, "advanced");
    await page.getByRole("tab", { name: "Setups", exact: true }).click();
    await expect(page.getByRole("button", { name: "My row setup", exact: true })).toBeVisible();
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(page.locator('[data-anatomy-state="ready"]')).toBeVisible({ timeout: 60_000 });
    await page.getByLabel("Selected equipment", { exact: true }).selectOption({ label: "Cable row" });
    await page.getByRole("tab", { name: "Timeline", exact: true }).click();
    await expect(slider).toBeInViewport();
    await expect(page.getByRole("tablist", { name: "Workshop tools", exact: true })).toBeInViewport();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: ".local-artifacts/workshop/improvements/mobile.png", fullPage: true });
    expect(errors).toEqual([]);
  } finally { await admin.auth.admin.deleteUser(account.data.user.id); }
});
