import { openWorkshopTool, selectWorkshopObject, jointField, selectWorkshopJoint } from "./workshop-menu.helpers";
import { randomUUID } from "node:crypto";
import { mkdirSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";
import { expect, test } from "@playwright/test";
import { machineDemoScene } from "../../src/lib/motion/studio-machines";

test.use({ launchOptions: { args: ["--use-gl=angle", "--use-angle=swiftshader"] } });
test.beforeEach(async ({ page }) => page.setDefaultTimeout(15_000));

test("keyframe pose, timing, deletion and undo persist without losing machine contact", async ({ page }) => {
  test.setTimeout(120_000);
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
  if (!["127.0.0.1", "localhost"].includes(new URL(url).hostname)) throw Error("Local fixtures required");
  const admin = createClient(url, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false } });
  const email = `timeline-${randomUUID()}@example.test`, password = "TimelineFixture2026!";
  const account = await admin.auth.admin.createUser({ email, password, email_confirm: true });
  if (account.error) throw account.error;
  const owner = createClient(url, process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!, { auth: { persistSession: false } });
  const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
  try {
    await owner.auth.signInWithPassword({ email, password });
    const scene = machineDemoScene("smith-machine", randomUUID());
    scene.keyframes = [scene.keyframes[0], scene.keyframes[8], scene.keyframes[16]];
    scene.studio!.objects[0].frames = [scene.studio!.objects[0].frames![0], scene.studio!.objects[0].frames![8], scene.studio!.objects[0].frames![16]];
    const created = await owner.rpc("create_workshop_exercise", { p_scene: scene });
    if (created.error) throw created.error;
    await page.setViewportSize({ width: 1440, height: 1100 });
    await page.goto("/sign-in");
    await page.getByLabel("Email", { exact: true }).fill(email); await page.getByLabel("Password", { exact: true }).fill(password);
    await page.getByRole("button", { name: "Sign in", exact: true }).click(); await expect(page).toHaveURL(/\/dashboard$/);
    await page.goto(`/my-exercises/${created.data}/workshop`);
    await openWorkshopTool(page, "Timeline");
    await page.getByRole("button", { name: "Finish · 2.40s", exact: true }).click();
    await selectWorkshopObject(page, "Smith machine");
    await openWorkshopTool(page, "Timeline");
    await page.getByRole("button", { name: "Edit keyframe", exact: true }).click();
    await expect(page.getByLabel("Bar height percent", { exact: true })).toHaveValue("0");
    await page.getByLabel("Bar height percent", { exact: true }).fill("42");
    await page.getByLabel("Keyframe time seconds").fill("3.005");
    await page.getByRole("button", { name: "Update time", exact: true }).click();
    await expect(page.getByRole("button", { name: "Pose 2 · 3.00s", exact: true })).toHaveAttribute("aria-pressed", "true");
    await expect(page.getByLabel("Bar height percent", { exact: true })).toHaveValue("42");
    await page.getByLabel("Keyframe time seconds").fill("4.8");
    await page.getByRole("button", { name: "Update time", exact: true }).click();
    await expect(page.getByRole("region", { name: "Selected keyframe" }).getByRole("alert")).toContainText("keep the frames in order");
    await page.getByLabel("Keyframe time seconds").fill("3.005");
    await page.getByRole("button", { name: "Update time", exact: true }).click();
    await page.getByRole("button", { name: "Save", exact: true }).click();
    await expect(page.getByText(/Saved at.*Private/)).toBeVisible();
    await page.reload(); await openWorkshopTool(page, "Timeline");
    await page.getByRole("button", { name: "Pose 2 · 3.00s", exact: true }).click();
    await expect(page.getByLabel("Keyframe time seconds")).toHaveValue("3.005");
    await page.getByRole("button", { name: "Edit keyframe", exact: true }).click();
    await expect(page.getByLabel("Bar height percent", { exact: true })).toHaveValue("42");
    mkdirSync(".local-artifacts/timeline", { recursive: true });
    await expect(page.locator('[data-anatomy-state="ready"]')).toBeVisible({ timeout: 60_000 });
    await page.screenshot({ path: ".local-artifacts/timeline/controls.png", fullPage: true });
    await page.getByRole("button", { name: "Delete keyframe", exact: true }).click();
    await expect(page.getByRole("button", { name: /^(Finish|Pose 2) ·/ })).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Delete keyframe", exact: true })).toBeDisabled();
    await page.getByRole("button", { name: "Undo", exact: true }).click();
    await expect(page.getByRole("button", { name: /^(Finish|Pose 2) ·/ })).toHaveCount(1);
    await page.getByRole("button", { name: /^Start ·/ }).click();
    await page.getByRole("button", { name: "Delete keyframe", exact: true }).click();
    await expect(page.getByRole("button", { name: "Start · 0.00s", exact: true })).toHaveAttribute("aria-pressed", "true");
    await expect(page.getByLabel("Bar height percent", { exact: true })).toHaveValue("42");
    await selectWorkshopObject(page, "Smith machine");
    await page.getByRole("button", { name: "Stop using machine", exact: true }).click();
    await selectWorkshopJoint(page, "Torso");
    await jointField(page, "x").fill("12");
    await page.getByRole("button", { name: "Save", exact: true }).click();
    await expect(page.getByText(/Saved at.*Private/)).toBeVisible();
    await page.reload(); await openWorkshopTool(page, "Timeline");
    await expect(page.getByRole("button", { name: /^(Finish|Pose 2) ·/ })).toHaveCount(0);
    await selectWorkshopObject(page, "Smith machine");
    await openWorkshopTool(page, "Timeline");
    await expect(page.getByLabel("Bar height percent", { exact: true })).toHaveValue("42");
    await selectWorkshopJoint(page, "Torso");
    await expect(jointField(page, "x")).toHaveValue("12");
    const sparse = structuredClone(scene);
    sparse.studio!.objects[0].frames = [sparse.studio!.objects[0].frames![0], sparse.studio!.objects[0].frames![2]];
    sparse.studio!.objects[0].frames[1].machinePosition = 0;
    const second = await owner.rpc("create_workshop_exercise", { p_scene: sparse });
    if (second.error) throw second.error;
    await page.goto(`/my-exercises/${second.data}/workshop`);
    await openWorkshopTool(page, "Timeline");
    await page.getByRole("button", { name: "Delete keyframe", exact: true }).click();
    await page.getByRole("button", { name: "Save", exact: true }).click();
    await expect(page.getByText(/Saved at.*Private/)).toBeVisible();
    await page.reload(); await openWorkshopTool(page, "Timeline");
    await expect(page.getByRole("button", { name: /^(Finish|Pose 2) ·/ })).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Delete keyframe", exact: true })).toBeDisabled();
    await page.getByRole("button", { name: "Edit keyframe", exact: true }).click();
    await expect(page.getByLabel("Bar height percent", { exact: true })).toHaveValue("50");
    const third = await owner.rpc("create_workshop_exercise", { p_scene: sparse });
    if (third.error) throw third.error;
    await page.goto(`/my-exercises/${third.data}/workshop`);
    await openWorkshopTool(page, "Timeline");
    await page.getByRole("button", { name: /^Return ·/ }).click();
    await page.getByRole("button", { name: "Delete keyframe", exact: true }).click();
    await page.getByRole("button", { name: "Save", exact: true }).click();
    await expect(page.getByText(/Saved at.*Private/)).toBeVisible();
    await page.reload(); await openWorkshopTool(page, "Timeline");
    await page.getByRole("button", { name: /^Return ·/ }).click();
    await page.getByRole("button", { name: "Edit keyframe", exact: true }).click();
    await expect(page.getByLabel("Bar height percent", { exact: true })).toHaveValue("50");
    await page.setViewportSize({ width: 390, height: 844 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    expect(errors).toEqual([]);
  } finally { await admin.auth.admin.deleteUser(account.data.user.id); }
});
